### ISSUE TITLE
Ellipsis session detail and expand

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#101]
## Overview (Required)
- We should add read more("続きを読む") function

| current | design |
|---|---|
| ![image](https://user-images.githubusercontent.com/1386930/50538441-3489ac00-0bb3-11e9-86a5-472782b019d8.png) | ![image](https://user-images.githubusercontent.com/1386930/50538445-4a976c80-0bb3-11e9-87ce-37fb0969e3c5.png) |

## Links
- https://gallery.io/projects/MCHbtQVoQ2HCZd9Pbpex4PVP/files/MCHtA7U1iMGr60CQdbvgFMCPHe-6adOX1IM (Please send request)

**Comment by a25max** [comment]
🙋

**Comment by jmatsu** [comment]
@a25max 
Thank you so much! Could you please address this issue?
