### ISSUE TITLE
Display the title in the title of the tool bar when scrolling on the session details screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#108]
## Overview (Required)
- Currently, the titile does not show in toolbar
![screenshot_20181231-123532](https://user-images.githubusercontent.com/1386930/50554142-9c95da80-0cf8-11e9-816d-5a6bd0506045.png)

## Links
-https://gallery.io/projects/MCHbtQVoQ2HCZd9Pbpex4PVP/files/MCHtA7U1iMGr649eY4pvpXHS096RuaGqQMU (Please send request)

**Comment by youmitsu** [comment]
🙋

**Comment by takahirom** [comment]
I think it is difficult. 🔥 Please tackle it 👍
