### ISSUE TITLE
Show notification when my session starts

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#115]
## Overview (Required)
 - Title says everything ⏲ 
 - Probably we can use implementation of 2018.

https://github.com/DroidKaigi/conference-app-2018/blob/master/app/src/main/java/io/github/droidkaigi/confsched2018/util/SessionAlarm.kt
https://github.com/DroidKaigi/conference-app-2018/pull/244

**Comment by syarihu** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks 😭 
Last year, nobody raised their hands for this issue 😭
