### ISSUE TITLE
Show firebase topic notification

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#116]
## Overview (Required)
- Show firebase topic notification 🔥 
- Probably we can use implementation of 2018.
- https://github.com/DroidKaigi/conference-app-2018/blob/a98b363c8bcfad43703bab28dd30649d51944444/app/src/main/java/io/github/droidkaigi/confsched2018/presentation/App.kt#L53
https://github.com/DroidKaigi/conference-app-2018/blob/a98b363c8bcfad43703bab28dd30649d51944444/app/src/main/java/io/github/droidkaigi/confsched2018/service/push/processor/NewPostProcessor.kt

**Comment by jmatsu** [comment]
let me grab this cuz notification testing is difficult for external members.
