### ISSUE TITLE
Change color of the search hit text on the search result

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#117]
## Overview (Required)
- title says everything
- blocked by https://github.com/DroidKaigi/conference-app-2019/issues/114

## Links
- https://github.com/DroidKaigi/conference-app-2018/pull/135

**Comment by atsuya046** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks 👍 Assigned 🔎🔍
