### ISSUE TITLE
Session share

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#121]
## Overview (Required)
- Currently, the share feature is not implemented.
![image](https://user-images.githubusercontent.com/1386930/50603524-18ad3f80-0efe-11e9-9499-2f31ce5b150e.png)
- Blocked by web (URL)

**Comment by jmatsu** [comment]
For now, it's okay to just share the only session web url as text.

**Comment by h3birth** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks 👍 Please add share feature to ActivityActionCreator.

**Comment by takahirom** [comment]
Assigned
