### ISSUE TITLE
Show current session tag

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#122]
## Overview (Required)
- Show tag like this.

![image](https://user-images.githubusercontent.com/1386930/50635256-d1be5900-0f94-11e9-9856-7c5037974442.png)

## Links
- https://gallery.io/projects/MCHbtQVoQ2HCZd9Pbpex4PVP/files/MCHtA7U1iMGr60CQdbvgFMCPQgTMxuy7EIA (Please send request)

**Comment by imtuann** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks 👍 Assigned 🆕
