### ISSUE TITLE
Create and use "visibleGone" binding adapter

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#131]
## Overview (Required)
- We can create "visibleGone" binding adapter. Like this

```kotlin
    @JvmStatic
    @BindingAdapter("visibleGone")
    fun showHide(view: View, show: Boolean) {
        view.visibility = if (show) View.VISIBLE else View.GONE
    }
```

## Links
- https://github.com/googlesamples/android-architecture-components/blob/17c315a050745c61ae8e79000bc0251305bd148b/GithubBrowserSample/app/src/main/java/com/android/example/github/binding/BindingAdapters.kt#L27
- https://github.com/DroidKaigi/conference-app-2019/search?q=View.VISIBLE+%3A+View.GONE&unscoped_q=View.VISIBLE+%3A+View.GONE

**Comment by kitwtnb** [comment]
🙋‍♂️

**Comment by jmatsu** [comment]
So cool. will you? @kitwtnb
