### ISSUE TITLE
Show movie and slide in session detail

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#134]
## Overview (Required)
- If app can get it link, we should show movie and slide link
![image](https://user-images.githubusercontent.com/1386930/50697092-9d29ca80-1084-11e9-96f0-e41ebca616c6.png)
![image](https://user-images.githubusercontent.com/1386930/50697203-e712b080-1084-11e9-958b-99956ccb3770.png)

## Links
- https://gallery.io/projects/MCHbtQVoQ2HCZd9Pbpex4PVP/files/MCHtA7U1iMGr60CQdbvgFMCPHe-6adOX1IM (Please send request)
- https://app.swaggerhub.com/apis-docs/jmatsu/DroidKaigi2019/1.0.0#/developers/timtable

**Comment by jmatsu** [comment]
On the dev server.

Day2 15:40:00~ `WiFi Direct + VpnServiceでSIM無しAndroidをWeb世界に社会復帰させる話` (Revive Android devices with no SIM to Internet world using WiFi Direct and VpnService") has the both of links.
Day1 15:40:00~ `Understanding  Kotlin Coroutines: コルーチンで進化するアプリケーション開発` (Understanding  Kotlin Coroutines: the advancements made in application development) has the video url only
Day1 16:00:00~ `詳解定期購入` (Deep dive into subscriptions) has the slide url only

**Comment by NUmeroAndDev** [comment]
🙋‍♂️
