### ISSUE TITLE
Kotlin Multiplatform API implementation

### ISSUE THREAD

**Issue by panpanini** [DroidKaigi/conference-app-2019#136]
## Overview (Required)
- In order to achieve #132, we should make the API implementation as a Kotlin Multiplatform library.

This will require separating pure Kotlin code from Java (eg: Dagger, etc), and bundling each into a jar, or a framework for Kotlin/Native

## Links
- https://kotlinlang.org/docs/reference/building-mpp-with-gradle.html

**Comment by kikuchy** [comment]
Just a question.
It there any plans to place iOS API implementation source codes?

Currently, Android API implementations are placed like below (ex. `data` directory).
It seems that we should make new modules like `api-impl-ios` separating from the Android implementation module.

```
data
├── api  (interfaces only)
│   └── src
│       ├── androidTest
│       ├── commonMain
│       ├── main
│       └── test
├── api-impl  (Android implementation only)
│   └── src
│       ├── main
│       └── test
```

JetBrains's example contains Android and iOS sources into one module (to provide `actual` implementations).  
https://github.com/JetBrains/kotlin-mpp-example/tree/master/greeting/src  
And we will be able to place iOS implementations like `data/api-impl/iosMain`

Which way repository owners are assuming?

**Comment by takahirom** [comment]
If we can, I want to do `data/api-impl/iosMain`.

**Comment by kikuchy** [comment]
I see. Thank you for replying!

**Comment by takahirom** [comment]
done. 👍
