### ISSUE TITLE
Add English resource for string resource on About screen.

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#142]
## Overview (Required)
- There is no English resource for string resource on About screen.

## Links
- https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/about/src/main/res/values/strings.xml

**Comment by kyoro** [comment]
🙋‍♀️

**Comment by takahirom** [comment]
Thank you 👍Assigned 🔡

**Comment by kyoro** [comment]
PR submitted 💪 
https://github.com/DroidKaigi/conference-app-2019/pull/233
