### ISSUE TITLE
Add a function to open Google map in "About screen"

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#143]
## Overview (Required)
- Probably we can implement that by launch intent.
![image](https://user-images.githubusercontent.com/1386930/50724788-5399b800-1136-11e9-96b5-db7e0d724a47.png)

**Comment by Hunachi** [comment]
🙋‍♀️

**Comment by jmatsu** [comment]
Thanks!
We will be waiting for your PR. 👍
