### ISSUE TITLE
Add staff list screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#144]
## Overview (Required)
- We can use that API https://droidkaigi2019-dev.appspot.com/api/staffs
- We can use layout for search list

https://gallery.io/projects/MCHbtQVoQ2HCZd9Pbpex4PVP/files/MCHtA7U1iMGr6_wk8XZwCNuDb4sy76tbjpM  (Please send request)
![image](https://user-images.githubusercontent.com/1386930/50724793-6613f180-1136-11e9-8553-8a4c1f16e44d.png)

**Comment by miga9** [comment]
I would love to work on this one 🙋‍♂️

**Comment by takahirom** [comment]
Thank you every year! I am longing for your PR 😄

**Comment by miga9** [comment]
Just a quick update, I should be able to publish a PR this weekend.

**Comment by miga9** [comment]
What's supposed to happen when user clicks on a row? Launch the profileUrl in webview?

**Comment by takahirom** [comment]
Thank you. I think that nothing should happen. If necessary we can also add later.

**Comment by miga9** [comment]
Thanks for responding!

Let me give you more info. I have added Staff class to `/model/src/commonMain/kotlin/Staff.kt`, API response classes to `/data/api/src/commonMain/kotlin/io/github/droidkaigi/confsched2019/data/api/response/`, and Room entity classes to `/data/db/src/commonMain/kotlin/io/github/droidkaigi/confsched2019/data/db/entity/`.

![screen shot 2019-01-19 at 10 33 09 am](https://user-images.githubusercontent.com/3074663/51428797-ec6c1100-1bd5-11e9-9e14-17e1e9d345b6.png)

In the same order as the 5 errors in the screenshot:

`/{path}/kaigi2019/feature/staff/build/generated/data_binding_base_class_source_out/debug/dataBindingGenBaseClassesDebug/out/io/github/droidkaigi/confsched2019/staff/databinding/ItemStaffBinding.java:26: error: cannot find symbol
  protected ItemStaffBinding(DataBindingComponent _bindingComponent, View _root,
                             ^
  symbol:   class DataBindingComponent
  location: class ItemStaffBinding
`

`/{path}/kaigi2019/feature/staff/build/generated/data_binding_base_class_source_out/debug/dataBindingGenBaseClassesDebug/out/io/github/droidkaigi/confsched2019/staff/databinding/ItemStaffBinding.java:59: error: cannot find symbol
      @Nullable DataBindingComponent component) {
                ^
  symbol:   class DataBindingComponent
  location: class ItemStaffBinding
`

`/{path}/kaigi2019/feature/staff/build/generated/data_binding_base_class_source_out/debug/dataBindingGenBaseClassesDebug/out/io/github/droidkaigi/confsched2019/staff/databinding/FragmentStaffSearchBinding.java:17: error: cannot find symbol
  protected FragmentStaffSearchBinding(DataBindingComponent _bindingComponent, View _root,
                                       ^
  symbol:   class DataBindingComponent
  location: class FragmentStaffSearchBinding
`

`/{path}kaigi2019/feature/staff/build/generated/data_binding_base_class_source_out/debug/dataBindingGenBaseClassesDebug/out/io/github/droidkaigi/confsched2019/staff/databinding/FragmentStaffSearchBinding.java:42: error: cannot find symbol
      @Nullable DataBindingComponent component) {
                ^
  symbol:   class DataBindingComponent
  location: class FragmentStaffSearchBinding`

`/{path}/kaigi2019/feature/staff/build/tmp/kapt3/stubs/debug/io/github/droidkaigi/confsched2019/staff/ui/item/StaffItem.java:26: error: Assisted injection requires at least one non-@Assisted parameter.
    public StaffItem(@org.jetbrains.annotations.NotNull()
           ^
`

**Comment by miga9** [comment]
It's still a mess, but I pushed my branch to my repo, if that helps. 
https://github.com/miga9/conference-app-2019/commit/10e3ad5fa7941b711054ad28747ada583e31121f

**Comment by takahirom** [comment]
Thank you 👍 
I have not checked it yet. But I am concerned about this error. If you don't have `@Inject` parameter, you can create Item by using a normal way. 
Databinding will also display an error if the other part is bad. 😭 

```
/{path}/kaigi2019/feature/staff/build/tmp/kapt3/stubs/debug/io/github/droidkaigi/confsched2019/staff/ui/item/StaffItem.java:26: error: Assisted injection requires at least one non-@Assisted parameter. public StaffItem(@org.jetbrains.annotations.NotNull() ^
```

```kotlin
class StaffItem(
    val staff: Staff
) : BindableItem<ItemStaffBinding>(staff.id.hashCode().toLong()) {
```

```kotlin
            items += result.staffs.map {
                StaffItem(it)
            }
```

**Comment by miga9** [comment]
It reduced the 5 errors down to 1. "Clean Project" and building again didn't work. `ItemStaffBinding` class seems to not recognize the `Staff` class import.

`kaigi2019/feature/staff/build/generated/source/kapt/debug/io/github/droidkaigi/confsched2019/staff/DataBinderMapperImpl.java:10: error: cannot find symbol
import io.github.droidkaigi.confsched2019.staff.databinding.ItemStaffBindingImpl;
                                                           ^
  symbol:   class ItemStaffBindingImpl
  location: package io.github.droidkaigi.confsched2019.staff.databinding`

**Comment by takahirom** [comment]
👀

**Comment by tomoya0x00** [comment]
Is the following error message displayed?

```
  シンボル:   クラス ItemStaffBindingImpl
  場所: パッケージ io.github.droidkaigi.confsched2019.staff.databinding
e: [kapt] An exception occurred: android.databinding.tool.util.LoggedErrorException: Found data binding errors.
****/ data binding error ****msg:Could not find accessor io.github.droidkaigi.confsched2019.model.Staff.imageUrl
file:D:\development\ghq\github.com\miga9\conference-app-2019\feature\staff\src\main\res\layout\item_staff.xml
loc:31:28 - 31:41
```

**Comment by takahirom** [comment]
Sometimes databinding will display important errors later. 😭

**Comment by takahirom** [comment]
Probably I can use `iconUrl` 👍

**Comment by miga9** [comment]
Ah yes! Printing the stacktrace by `./gradlew :frontend:android:assembleDebug --stacktrace` gave me that detail. It still has similar errors, but I think I can figure it out now.

Thank you for your time and the help! @takahirom @tomoya0x00

**Comment by takahirom** [comment]
Please feel free to ask us if you have any questions. 👍

**Comment by miga9** [comment]
I was able to get it to compile. I had to manually add the import statements for `io.github.droidkaigi.confsched2019.ext.android.changed` although my IDE still shows in red as it doesn't recognize.

**Comment by takahirom** [comment]
It is a common problem with this project. Close the project and return to the "Welcome to Android Studio" screen. So when you mouse over the project, press the close button that appears. And it should be displayed again by reopening the project.

**Comment by takahirom** [comment]
I opened that issue.
https://github.com/DroidKaigi/conference-app-2019/issues/548

**Comment by takahirom** [comment]
I am sorry to have changed, but I do not want to display the initial letter and I would like to use the order returned from the API. 🙏
