### ISSUE TITLE
Add "about screen" to privacy policy feature 

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#145]
## Overview (Required)
- You can use ActivityActionCreator.openUrl()
![image](https://user-images.githubusercontent.com/1386930/50724820-bbe89980-1136-11e9-9016-025ded0f0127.png)

## Links
- http://www.association.droidkaigi.jp/privacy.html

**Comment by kichinaga** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned 👮
