### ISSUE TITLE
Add license feature

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#146]
## Overview (Required)
- You can use https://developers.google.com/android/guides/opensource
![image](https://user-images.githubusercontent.com/1386930/50724835-04a05280-1137-11e9-860a-d6fc8a4d630e.png)

**Comment by NUmeroAndDev** [comment]
I would like to implement this function.

I want to ask a few questions before that.
- Call `startActivity` from the class of `[AboutSection](https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/about/src/main/java/io/github/droidkaigi/confsched2019/about/ui/item/AboutSection.kt)`?
- Which AndroidManifest do you write OssLicensesActivity?
[android feature](https://github.com/DroidKaigi/conference-app-2019/blob/master/frontend/android/src/main/AndroidManifest.xml)?

**Comment by takahirom** [comment]
Can you add that Activity here? 👀 
https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/about/src/main/AndroidManifest.xml

**Comment by takahirom** [comment]
> Call startActivity from the class of [AboutSection](https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/about/src/main/java/io/github/droidkaigi/confsched2019/about/ui/item/AboutSection.kt)?
Let me think. Can we use navigation architecture component?

**Comment by NUmeroAndDev** [comment]
@takahirom 
>Can you add that Activity here? 👀
>https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/about/src/main/AndroidManifest.xml
OK. I will add to feature/about/src/main/AndroidManifest.xml

>Can we use navigation architecture component?

[oss-licenses-plugin](https://developers.google.com/android/guides/opensource) is provided only for activity, I think navigation can not be used. 😢
