### ISSUE TITLE
Prevent click tag in session detail

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#148]
## Overview (Required)
- Now chips are clickable
- You can check session list chip implementation https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/session/src/main/res/layout/item_session.xml#L102
![image](https://user-images.githubusercontent.com/1386930/50725102-d8d39b80-113b-11e9-902a-ed41e1d1d669.png)

**Comment by TomoyaShibata** [comment]
Hi!

By clicking on chips the search function by tag seemed to work.
Does that mean you want to disable clicking because there is no function?

**Comment by takahirom** [comment]
> Does that mean you want to disable clicking because there is no feature?
Yes! I want to disable clicking! ✋

**Comment by sobaya-0141** [comment]
担当させて頂けますか？

**Comment by takahirom** [comment]
Thanks! Assigned 🐁
