### ISSUE TITLE
Make it possible to go from the session details to the floor map

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#149]
## Overview (Required)
- When clicking this icon, please navigate to the floor map
![image](https://user-images.githubusercontent.com/1386930/50725138-63b49600-113c-11e9-95df-1ce221ee9586.png)

**Comment by TomoyaShibata** [comment]
🙋

**Comment by jmatsu** [comment]
@TomoyaShibata 
So quick 💯 Could you please tackle this issue too?

**Comment by takahirom** [comment]
@TomoyaShibata 
How are you progressing? (just i want to say it 😄 )

**Comment by TomoyaShibata** [comment]
@takahirom 

Sorry for the late reply! 🙇 
My work has been busy this past week, and since I have not returned home, the development environment did not exist.
I am planning to submit some pull request in a few days.
I will report it as soon as the problem occurs.
