### ISSUE TITLE
Add tag simultaneous interpretation(同時通訳)

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#152]
## Overview (Required)
- Add tag in session list and session detail.
![image](https://user-images.githubusercontent.com/1386930/50725317-52b95400-113f-11e9-9cf6-cc86cb5ee3f4.png)
![image](https://user-images.githubusercontent.com/1386930/50725352-a7f56580-113f-11e9-8831-8800786d5a64.png)

**Comment by atsuya046** [comment]
🙋‍♂️
