### ISSUE TITLE
BottomAppBar does not disappear on session details that can not be scrolled

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#153]
## Overview (Required)
- BottomAppBar does not disappear on session details that can not be scrolled

![image](https://user-images.githubusercontent.com/1386930/50725386-35d15080-1140-11e9-8471-32cdd466b8f6.png)

**Comment by androhi** [comment]
I want to fix this issue.

**Comment by jmatsu** [comment]
Depending on the scroll behavior looks better for me.
@panpanini @takahirom how about you?

**Comment by takahirom** [comment]
I think so, But is it difficult?

**Comment by androhi** [comment]
@jmatsu Sorry, I meant the case of the screen that can not scrolled. (according to the title.)

**Comment by jmatsu** [comment]
oh, sorry.  I see. I prefer to `disappear when tap screen` then.

**Comment by androhi** [comment]
Thanks!! me too!

**Comment by takahirom** [comment]
It is good to hide the Bar without scrolling when you slide your finger up and down. It may be difficult.
So `disappear when tap screen` is ok 🙆

**Comment by androhi** [comment]
Thanks!! I will fix it like that. 😄
