### ISSUE TITLE
Fix session list is not displayed

### ISSUE THREAD

**Issue by tomoya0x00** [DroidKaigi/conference-app-2019#157]
## Overview (Required)
- I don't know how to reproduce.

![screenshot_20190105-184656](https://user-images.githubusercontent.com/5106629/50726581-b7ca7500-1152-11e9-8eec-3aa6a56026dc.png)

## Links
-

**Comment by kafumi** [comment]
I've figured out the root cause. Let me propose a possible fix later.

**Comment by jmatsu** [comment]
Lovely! Let us assign this issue to you for now. 🥇
