### ISSUE TITLE
Fix possible filter operation even if the bottom sheet of the session list is open

### ISSUE THREAD

**Issue by tomoya0x00** [DroidKaigi/conference-app-2019#159]
## Overview (Required)
![can_scroll](https://user-images.githubusercontent.com/5106629/50727167-55757280-115a-11e9-990a-157e5d977eb6.gif)

## Links
-

**Comment by ronnnnn** [comment]
🙋‍♀️

**Comment by takahirom** [comment]
Thanks 👍 Assigned 📺
