### ISSUE TITLE
Display favorite buttons with codelabs and change so that they can be favorite

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#164]
## Overview (Required)
-
![image](https://user-images.githubusercontent.com/1386930/50731992-576c1f80-11b4-11e9-9c07-4da395dcd5c7.png)

- We can use session#sessionType

```
  enum class SessionType {
        @SerializedName("normal")
        Normal,
        @SerializedName("welcome_talk")
        WelcomeTalk,
        @SerializedName("reserved")
        Reserved,
        @SerializedName("codelabs")
        Codelabs,
        @SerializedName("fireside_chat")
        FiresideChat,
        @SerializedName("lunch")
        Lunch,
        @SerializedName("break")
        Break,
        @SerializedName("after_party")
        AfterParty
    }
```

## Links
- https://droidkaigi2019-dev.appspot.com/api/timetable

**Comment by kirimin** [comment]
I'll try to do this one! ✋

**Comment by takahirom** [comment]
I think it is a little hard 👍 
Assigned
Please ask me anytime

**Comment by kirimin** [comment]
OMG, Really? lol
Anyway I'll try. 💪 

...Sorry if I can't complete this.

**Comment by takahirom** [comment]
The service session id is not int. And favorite session id is defined as int. 
Perhaps I think it should be able to handle it as a String, but if something happens, please say it 🙇 
https://github.com/DroidKaigi/conference-app-2019/blob/master/data/firestore-impl/src/main/java/io/github/droidkaigi/confsched2019/data/firestore/FirestoreImpl.kt#L18

**Comment by takahirom** [comment]
https://droidkaigi2019-dev.appspot.com/api/timetable
