### ISSUE TITLE
Sometime unneeded animation myplan tab

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#167]
## Overview (Required)
- You can see gif
![animation](https://user-images.githubusercontent.com/1386930/50732059-f34a5b00-11b5-11e9-9818-86e99e1022bc.gif)

**Comment by shiraji** [comment]
How did you translate tabs? Swipe? Tapping tab names? or other ways?

**Comment by takahirom** [comment]
Swipe
Essential Phone Android 9.0 🤔

**Comment by panpanini** [comment]
I guess raising the number of fragments stored in memory might fix this? 

https://developer.android.com/reference/android/support/v4/view/ViewPager.html#setOffscreenPageLimit(int)

**Comment by takahirom** [comment]
I do not know the cause, but it may be okay to fix it. It becomes slightly inefficient memory, but it may be better than animation😂

**Comment by jmatsu** [comment]
That might be able to hide this behavior, but it does not seem to me that it's an essential fix. It looks okay as a hotfix, of course.
Setting no transition animation and no transformation would be better though I dunno if it works.

**Comment by kafumi** [comment]
I believe the main problem here is that the bottom sheet on MyPlan is collapsed when swiping from MyPlan to Day2. The animation when swiping from Day2 to MyPlan is the result of the previous collapse.

Here is my observation:

- Reproducibility depends on swipe angle
- The issue is never reproduced when user starts swipe on RecyclerView
  - I guess that is the reason why this issue can happen only with MyPlan tab

![svid_20190110_002923_1](https://user-images.githubusercontent.com/12084705/50922140-c45f0e00-146f-11e9-9e90-f569d4a67468.gif)

**Comment by gen0083** [comment]
It seems to be more reproducible by swiping diagonally down at the margin between list items.
On MyPlan tab, it reproduces to swipe on below area of list item too.
Therefore, I think that there are more reproducible with MyPlan tab.

![reproduce_step](https://user-images.githubusercontent.com/7608725/51102952-4a8aa400-1824-11e9-8026-d45ef4270f97.gif)

**Comment by maripiyoko** [comment]
May I try this issue?

I think there are two ways to fix.

1. Change BottomSheetBehavior.STATE_EXPANDED timing

Currently BottomSheet is back to expand when the page is selected.
How about change the expanding timing when the page is deselected?
If its OK, it looks like this.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1080848/51320480-53d57400-1aa3-11e9-9b8a-29408777a613.gif)

(once the bottom sheet is collapse a bit, but back to expand)
But maybe it still looks a bit awkward. 🤔 

---

2. Cancel or disable users swipe action based on the tab view state

I guess adding `onInterceptTouchEvent` to BottomSheet like this entry.
https://blog.k3n.link/entry/lockable-bottom-sheet-behavior
Also need to store pageView state.
This way, need to fix a bit.

**Comment by e10dokup** [comment]
@maripiyoko Thank you for having a look at this issue! Please take this issue!

**Comment by e10dokup** [comment]
@maripiyoko If you can, we would like to you implement it with the 2nd way!

> Cancel or disable users swipe action based on the tab view state

**Comment by maripiyoko** [comment]
OK! I'll try 2nd way 💪

**Comment by kafumi** [comment]
@takahirom @maripiyoko I found this issue happens only when user starts swipe on `RecyclerView`. I didn't understand the reason, though.

As the option 3, how about using `android:layout_height="wrap_content"` for `RecyclerView` on bottom sheet?

```diff
diff --git a/feature/session/src/main/res/layout/fragment_bottom_sheet_sessions.xml b/feature/session/src/main/res/layout/fragment_bottom_sheet_sessions.xml
index 205bd1fe..85ff9ca2 100644
--- a/feature/session/src/main/res/layout/fragment_bottom_sheet_sessions.xml
+++ b/feature/session/src/main/res/layout/fragment_bottom_sheet_sessions.xml
@@ -118,18 +118,24 @@
             app:layout_constraintTop_toBottomOf="@id/sessions_list_header"
             />

-        <androidx.recyclerview.widget.RecyclerView
-            android:id="@+id/sessions_recycler"
-            android:orientation="vertical"
+        <FrameLayout
             android:layout_width="0dp"
             android:layout_height="0dp"
-            app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager"
             app:layout_constraintBottom_toBottomOf="parent"
             app:layout_constraintEnd_toEndOf="parent"
             app:layout_constraintStart_toStartOf="parent"
             app:layout_constraintTop_toBottomOf="@id/sessions_list_header"
-            tools:listitem="@layout/item_session"
-            />
+            >
+
+            <androidx.recyclerview.widget.RecyclerView
+                android:id="@+id/sessions_recycler"
+                android:orientation="vertical"
+                android:layout_width="match_parent"
+                android:layout_height="wrap_content"
+                app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager"
+                tools:listitem="@layout/item_session"
+                />
+        </FrameLayout>

         <LinearLayout
             android:id="@+id/sessions_empty_state_view"
```

I understand this solution is not elegant, but it probably works...

**Comment by takahirom** [comment]
Will not it disable recycling of RecyclerView?
I want to check that the childcount of RecyclerView is the same as the displayed number.

**Comment by takahirom** [comment]
@maripiyoko Can you do that ? 🙏
