### ISSUE TITLE
Delete thin line in the tab title

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#172]
## Overview (Required)
- Probably you can see it in device
![image](https://user-images.githubusercontent.com/1386930/50733168-ea648400-11cb-11e9-97c9-1db9a31212dd.png)
![image](https://user-images.githubusercontent.com/1386930/50733178-0e27ca00-11cc-11e9-9c96-0112d52f7cd2.png)

**Comment by rmakiyama** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Please delete it 😭

**Comment by jmatsu** [comment]
@rmakiyama, thanks for your contribution.
Please send a patch this year too :)
