### ISSUE TITLE
Restore searched text when return from detail screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#176]
## Overview (Required)
- When session -> search -> session detail -> back
- Searched text is cleard. We should restore it.
![image](https://user-images.githubusercontent.com/1386930/50733639-66fb6080-11d4-11e9-8f09-c3762bc479d7.png)

- We want to keep the inputted text
![search](https://user-images.githubusercontent.com/5106629/50738023-d6904080-1212-11e9-85f5-d9e8869aa21f.gif)

**Comment by rei-m** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks!Assigned 🔍
