### ISSUE TITLE
Apply SearchView design

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#178]
## Overview (Required)
- Even if it is not as designed, I want to delete the image here.
design
![image](https://user-images.githubusercontent.com/1386930/50735883-c79c9480-11f8-11e9-8977-b86e950d320b.png)
current
![image](https://user-images.githubusercontent.com/1386930/50735891-edc23480-11f8-11e9-9cd1-35680474b384.png)

**Comment by bowyer-app** [comment]
🙋

**Comment by takahirom** [comment]
Thanks! I think SearchView is difficult😂
