### ISSUE TITLE
Add search speaker initial index

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#179]
## Overview (Required)
- Please add A B C...
Design
![image](https://user-images.githubusercontent.com/1386930/50736011-9c1aa980-11fa-11e9-8ef5-e157deee6b73.png)
Current
![image](https://user-images.githubusercontent.com/1386930/50736006-84dbbc00-11fa-11e9-9883-f7effe5d9cbe.png)
## Links
- design https://gallery.io/projects/MCHbtQVoQ2HCZd9Pbpex4PVP/files/MCHtA7U1iMGr6_wk8XZwCNuDb4sy76tbjpM  (Please send request)

You can use 2018 decoration
https://github.com/DroidKaigi/conference-app-2018/blob/master/app/src/main/java/io/github/droidkaigi/confsched2018/presentation/common/itemdecoration/StickyHeaderItemDecoration.kt

**Comment by kiuchikeisuke** [comment]
I try this! ✋

**Comment by takahirom** [comment]
@kiuchikeisuke 
Sorry, I lost your message 🙇 
Assigned 👍

**Comment by takahirom** [comment]
@kiuchikeisuke 
Thank you for the question 🙏 
I talk to Designer.And you can check the design. Can you tackle this?
![image](https://user-images.githubusercontent.com/1386930/50918293-26753e80-1483-11e9-8a98-8f51058c7ed1.png)

https://gallery.io/projects/MCHbtQVoQ2HCZd9Pbpex4PVP/files/MCHtA7U1iMGr6-ZF5RXVf1KRWr8VHz3wbOk (Please send request)

**Comment by takahirom** [comment]
Sorry I miss your comment 🙇
