### ISSUE TITLE
Expand top touch area for session item top and bottom

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#181]
## Overview (Required)
- I want to fix only the tap area without changing the appearance.
- Expand top touch area for session item top and bottom. We can reduce the bottom touch area.
![image](https://user-images.githubusercontent.com/1386930/50736251-68418300-11fe-11e9-8fbe-a9aa27c466c9.png)
- Please be aware that time must come at the same position as the title.
![image](https://user-images.githubusercontent.com/1386930/50736271-b3f42c80-11fe-11e9-9b0e-4ba23b37ab10.png)

**Comment by yurihondo** [comment]
🙋

**Comment by takahirom** [comment]
Thanks! Assigned 🔝
