### ISSUE TITLE
Remove search menu icon when not session top screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#183]
## Overview (Required)
- It is hidden but it exists.
- You can use `setHasOptionsMenu ` and `onCreateOptionsMenu` like SearchFragment
https://github.com/DroidKaigi/conference-app-2019/blob/3851bb4c471b0b20dfc48789232c4bc96edd73e5/feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SearchFragment.kt#L55
![image](https://user-images.githubusercontent.com/1386930/50736797-1d773980-1205-11e9-98df-7b3edd30676e.png)

**Comment by kazumax1218** [comment]
🙋‍♂️
