### ISSUE TITLE
Delete unused textMinTop property in SessionsItemDecoration class

### ISSUE THREAD

**Issue by tomoya0x00** [DroidKaigi/conference-app-2019#186]
## Overview (Required)
- We forgot to delete the property which is no longer used
![textmintop](https://user-images.githubusercontent.com/5106629/50737560-28829780-120e-11e9-9a22-0c61cdf87f1a.PNG)

**Comment by verno3632** [comment]
🙋

**Comment by jmatsu** [comment]
Thank you, @verno3632 . Please grab this :)

**Comment by takahirom** [comment]
Sorry🙇
It is fixed by https://github.com/DroidKaigi/conference-app-2019/pull/223

**Comment by takahirom** [comment]
I am looking forward to the next PR!
