### ISSUE TITLE
Remove last item divider on About screen

### ISSUE THREAD

**Issue by e10dokup** [DroidKaigi/conference-app-2019#188]
## Overview (Required)
- Divider on About Screen set to every items
- Remove divider set to last item
- This issue will be fixed to modify `DottedItemDecoration#onDrawOver`
    - https://github.com/DroidKaigi/conference-app-2019/blob/070ca0d09f3cfe7e926e94ca763336c8501a6817/feature/about/src/main/java/io/github/droidkaigi/confsched2019/about/ui/widget/DottedItemDecoration.kt

<img src="https://user-images.githubusercontent.com/5158413/50737764-45b86580-1210-11e9-9fa8-6879596bc17a.png" width="480" />

**Comment by dnc-pop30** [comment]
🙋

**Comment by jmatsu** [comment]
Thanks @dnc-pop30 , we assigned this issue to you. :)
