### ISSUE TITLE
Apply design when MyPlan is empty

### ISSUE THREAD

**Issue by tomoya0x00** [DroidKaigi/conference-app-2019#193]
## Overview (Required)
- current
![device-2019-01-07-003523](https://user-images.githubusercontent.com/5106629/50738138-2ae7f000-1214-11e9-820a-f40903be64ad.png)

- design
![top_myplan_blank](https://user-images.githubusercontent.com/5106629/50738121-068c1380-1214-11e9-8987-b5e108ca4ba2.png)

## Links
- https://gallery.io/projects/MCHbtQVoQ2HCZd9Pbpex4PVP/files/MCHtA7U1iMGr6907YDmqSpauXct6sWybT4I (Please send request)

**Comment by kumamotone** [comment]
:raising_hand_man:

**Comment by jmatsu** [comment]
@kumamotone 
Thank you so much! Please take it. 🙏

**Comment by kumamotone** [comment]
I can't find the string `お気に入りのセッションを登録すると\nあなた専用のプランを作ることが\nできます。` of English version.
Does it have been prepared somewhere or should we translate on one's own?

How about this: `Let\'s make your own plan\nby tapping session\'s bookmark button.`

I'm not too sure whether this sentence is grammarly correct and natural.
Can someone help me?

**Comment by panpanini** [comment]
How about something like this?
```
Add sessions to your plan\nby tapping the bookmark button.
```

**Comment by kumamotone** [comment]
@panpanini This sounds more natural 😻I'll use this. Thank you!
