### ISSUE TITLE
Use outlined icon instead of filled icon

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#194]
## Overview (Required)
- We can use the outlined material design icon

design
![image](https://user-images.githubusercontent.com/1386930/50738200-b19ccd00-1214-11e9-884f-8dd2cebcf1a9.png)

current
![image](https://user-images.githubusercontent.com/1386930/50738192-a21d8400-1214-11e9-8a3c-c6ad7793d019.png)

https://material.io/tools/icons/?search=settin&style=outline

![image](https://user-images.githubusercontent.com/1386930/50738215-cd07d800-1214-11e9-8ac1-1d47b74310d3.png)

## Links
- https://material.io/tools/icons/?search=settin&style=outline
- https://gallery.io/projects/MCHbtQVoQ2HCZd9Pbpex4PVP/files/MCGlwjLTZEdC13BTGEnixeIN (Open and Please request permission)

**Comment by NUmeroAndDev** [comment]
🙋‍♂️
