### ISSUE TITLE
Fix hamburger icon and title misaligned

### ISSUE THREAD

**Issue by tomoya0x00** [DroidKaigi/conference-app-2019#196]
## Overview (Required)
- Probably the height of the Toolbar is incorrect

![toolbar](https://user-images.githubusercontent.com/5106629/50738573-d09d5e00-1218-11e9-843f-f4f7bc9b28c4.png)

## Links
- https://gallery.io/projects/MCHbtQVoQ2HCZd9Pbpex4PVP/files/MCHtA7U1iMGr649eY4pvpXHSGVscGYz7Lus (Please send request)

**Comment by a25max** [comment]
🙋

**Comment by takahirom** [comment]
You are fist assigned person! Thanks! Assigned
