### ISSUE TITLE
Same signing key for deploygate and local build

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#20]
It is very convenient.
You can do like this.
https://github.com/DroidKaigi/conference-app-2018/blob/master/app/build.gradle.kts#L61

**Comment by matsujun** [comment]
🙋

**Comment by jmatsu** [comment]
@matsujun thank you so much!

**Comment by jmatsu** [comment]
If you have any question, please feel free to ask us.
