### ISSUE TITLE
When filtering, session such as Hall A / B and Room 5 code lab and lunch is displayed

### ISSUE THREAD

**Issue by granoeste** [DroidKaigi/conference-app-2019#231]
## Overview (Required)
- When filtering, session such as Hall A / B and Room 5 code lab and lunch is displayed. 
- Is it a specification?

**Comment by takahirom** [comment]
Sorry, let me think

**Comment by jmatsu** [comment]
As we talked in person, this is by design. Thanks for sharing your notice!
