### ISSUE TITLE
Can't run connectedAndroidTest

### ISSUE THREAD

**Issue by sys1yagi** [DroidKaigi/conference-app-2019#234]
## Overview (Required)

I tried run androidTest (`./gradlew connectedAndroidTest`) but I got error like below. 🤔 

```bash
/Users/toshihiroyagi/ghq/github.com/sys1yagi/conference-app-2019/data/db/src/androidTest/java/io/github/droidkaigi/confsched2019/ui/ExampleInstrumentedTest.java:4: エラー: パッケージandroidx.testは存在しません
import androidx.test.InstrumentationRegistry;
                    ^
```

## Links

none

**Comment by takahirom** [comment]
Nice catch 👍

**Comment by sys1yagi** [comment]
It seems to be caused by copying a dummy test code to a module which is not supposed to use androidTest. ex data, db module ...
And all AndroidTest code is still empty.

So, I will delete the androidTest which will cause compile error first. 
is it okay?

**Comment by takahirom** [comment]
OK 🙆‍♂️
