### ISSUE TITLE
Rethink how to inject Coroutine Dispacthers

### ISSUE THREAD

**Issue by jmatsu** [DroidKaigi/conference-app-2019#236]
## Overview (Required)

- @sys1yagi submitted his great idea for this matter via https://github.com/DroidKaigi/conference-app-2019/pull/230
- Now we are thinking we should refine the current injection approach for Coroutine Dispatchers
- ~We have multiple choices to tackle this issue though, after the rough discussion, we have gotten the conclusion that kotlinx's coroutine-testing is better for now. (But this does not mean the method has been decided.)~

After @sys1yagi 's investigation, corouting-testing is supporting only Main dispatcher so the current way looks the best for now. Thank you so much.

#### The current mechanism

*Pros*

- We can restrict authors to set dispatchers only from test code.
- Looks similar approach of the official coroutine testing. ref: https://github.com/Kotlin/kotlinx.coroutines/blob/master/core/kotlinx-coroutines-test/README.md
  It would be easy to adopt new testing methods by tracking the library even if they would change the test strategy.

*Cons*

- *Handler* might be redundant. This logic and naming do not make sense in the production code as for this matter.
- To set *a dispatcher* is what we want to do, but it looks like the code wants to specify *a handler*.

#### AppCoroutineDispatchers

*Pros*

- Be simple.
- We can explicitly specify Dispatcher.
- Don't need to reset dispatchers as long as each test cases re-build DI graph and so on.
- The performance would be slightly better than the current mechanism.

*Cons*

- The class is kinda mutable so we can change a dispatcher even in the production code. (Of course, it's meaningless though)
- We need to touch the root node of the DI graph for integration testings, i.e. we should know the root provider of the dispatcher holder in the test case
- Some functions become ugly...

```
@MainThread fun <T> ReceiveChannel<T>.toLiveData(
    defaultValue: T? = null,
    appCoroutineDispatchers: AppCoroutineDispatchers // wow...
): LiveData<T>
```

#### corouting-testing

*Pros*

- The official way so it's reliable, I believe.
- It would work fine even for the 3rd party libraries which use Kotlin Coroutine

*Cons*

- ExperimentalCoroutinesApi
- Only Main dispatcher works....?

## Links

- https://github.com/DroidKaigi/conference-app-2019/pull/230
- https://github.com/DroidKaigi/conference-app-2019/pull/230#issuecomment-452161629
- https://github.com/DroidKaigi/conference-app-2019/pull/230#issuecomment-452162826
- https://github.com/Kotlin/kotlinx.coroutines/blob/master/core/kotlinx-coroutines-test/README.md

**Comment by sys1yagi** [comment]
Additional information on the coroutine-test.

## pros

- Dispatchers.setMain can only be accessed with test scope. It can keep clean production code.

## cons

- Supports only the main dispatcher. You cannot replace Dispatchers.IO etc.
- `coroutine-test` replace implicitly MainCoroutineDispatcher to TestMainDispatcher. So, you have to call "Dispatchers.setMain()", If your target code of testing using Dispatchers.Main.

**Comment by sys1yagi** [comment]
For now, CoroutinePlugin(The current mechanism) seems a good way to keep the code flexible and clean.

**Comment by jmatsu** [comment]
Oh my...thank you for your dedicated investigation. 🆒

**Comment by jmatsu** [comment]
I've added the conclusion to the description Let me close this.

**Comment by jmatsu** [comment]
I found the opinion of one of Coroutine authors for dispatcher injection stuff. 
https://github.com/Kotlin/kotlinx.coroutines/issues/810#issuecomment-439927255

I agreed to this thought. As a core library, the plugin system is not suitable. It does not mean libraries should not introduce the plugin system.
