### ISSUE TITLE
Upgrade Gradle to 5.1

### ISSUE THREAD

**Issue by KeithYokoma** [DroidKaigi/conference-app-2019#241]
## Overview (Required)
- Include tasty updates in Gradle 5.1 to make the build more friendly with Kotlin DSL and faster.

## Links
- Release Note: https://docs.gradle.org/5.1/release-notes.html
- Migration Guide from 4.x to 5.1: https://docs.gradle.org/5.1/userguide/upgrading_version_4.html

**Comment by takahirom** [comment]
Currently, the stable version of the Android Gradle Plugin is not supported Gradle 5.1.
