### ISSUE TITLE
The icons on the status bar are disappears if it overlaps with the drawer

### ISSUE THREAD

**Issue by yurihondo** [DroidKaigi/conference-app-2019#269]
## Overview (Required)
The cause of this issue is that the drawer is overlapped the status bar and 
the icons are assimilated with the background color of the drawer.
For example, you can solve this issue by changing a color of the icons on the status bar when pulling out the drawer.

## Step by steps
1. Launch app
2. Open left side drawer
3. Check the notification icon which overlapped the drawer

### Screenshot
| Step1 | Step2 | 
|--------|--------|
| <img src="https://user-images.githubusercontent.com/33515193/50847399-d6c84180-13b4-11e9-9bf1-dbf4fd114405.png" width="320px"> | <img src="https://user-images.githubusercontent.com/33515193/50847816-e300ce80-13b5-11e9-9b60-94e5f9beadef.png" width="320px">|

## Actual result
The icons on the status bar overlapping with the drawer has disappeared

## Expected result
The icons on the status bar are not disappears.

## Links
 - reference
https://stackoverflow.com/questions/30075827/android-statusbar-icons-color

**Comment by takahirom** [comment]
Since it is not a big problem so far,
If it is not a bad code and the design seems to be okay, I would like to put this function into the application. 👍

**Comment by kafumi** [comment]
(left picture) If changing the color of status bar icons to darker while drawer is opened, their visibility is improved on drawer area. However, it might be worsen outside of drawer area.

(right picture) How about changing status bar background color while drawer is opened instead?

<img width="300" src="https://user-images.githubusercontent.com/12084705/51056306-78939c80-1608-11e9-962f-bdcf287924fd.jpg" /> <img width="300" src="https://user-images.githubusercontent.com/12084705/51056307-78939c80-1608-11e9-980e-d0097b02a183.jpg" />

**Comment by takahirom** [comment]
Changing the status bar probably looks good as well👍
Since I can not decide not to see the actual actions, can you make it with the behavior you think seems to be good and let me send a PR?🙏

**Comment by kafumi** [comment]
Sure. Let my try it!

**Comment by takahirom** [comment]
Thanks! I assigned you 😉
