### ISSUE TITLE
Wrong klock DateTime conversion.

### ISSUE THREAD

**Issue by nukka123** [DroidKaigi/conference-app-2019#272]
## Overview (Required)

Several klock `DateTime` conversion code seems wrong...

### Superficial problem.

The time when "Go to survey" is displayed is shifted.

1) Set Android device time like as 2019 Feb. 7, 21:00 (GMT+9:00 (Japan Standard Time))
2) launch droidkaigi app.

we expected following behavior.
All Day1 Session is finished. ("Go to survey" is displayed).

but actual result is as follows.
The session since lunch has not finished yet. ("Go to survey" is NOT displayed).

![screenshot](https://user-images.githubusercontent.com/29206446/50853589-f3b94080-13c5-11e9-85db-999fe81eaabe.png)

### Code problem.

**SessionDataMapperExt.kt**

```
            stime = dateFormat.parse(startsAt).utc.unixMillisLong,
            etime = dateFormat.parse(endsAt).utc.unixMillisLong,
```

When `endsAt` is "2019-02-07T11:50:00", `etime` indicate 2019 Feb 07 11:50:00 (GMT+0:00).
But, the true meaning of "2019-02-07T11:50:00" in droidkaigi api response is 2019 Feb 07 11:50:00 (GMT+9:00).

**Session.kt**

```
    val isFinished: Boolean
        get() = DateTime.nowUnixLong() > endTime.unixMillisLong
```

When `endsAt` is "2019-02-07T11:50:00", `endTime` indicate 2019 Feb 07 11:50:00 (GMT+0:00).
This time same as 2019 Feb 07 20:50:00 (GMT+9:00 (Japan Standard Time)).

```
        append(startTime.format("hh:mm"))
        append(" - ")
        append(endTime.format("hh:mm"))
```

And more, "hh" means 12-hour notation. (see Session Detail screen)
If we expect 24-hour notation, specify "HH".

### Appendix: Basic test code.

```
        val t1a: DateTimeTz =
            DateFormat("""yyyy-MM-dd'T'HH:mm:ss""").parse("2019-02-07T11:50:00")
        assertEquals(TimezoneOffset(0.0), t1a.offset)
        assertEquals(11, t1a.hours)
        assertEquals("11:50", t1a.format("HH:mm"))
        assertEquals(1549540200000, t1a.utc.unixMillisLong)

        val t1b: DateTime = t1a.utc
        assertEquals(11, t1b.hours)
        assertEquals("11:50", t1b.format("HH:mm"))

        val t1c: DateTimeTz = t1b.toOffset(TimezoneOffset((9*60*60*1000).toDouble()))
        assertEquals(TimezoneOffset((9*60*60*1000).toDouble()), t1c.offset)
        assertEquals(20, t1c.hours)
        assertEquals("08:50", t1c.format("hh:mm"))
        assertEquals("20:50", t1c.format("HH:mm"))
        assertEquals(t1a.utc.unixMillisLong, t1c.utc.unixMillisLong)

        val t2a: DateTimeTz =
            DateFormat("""yyyy-MM-dd'T'HH:mm:ssxxx""").parse("2019-02-07T11:50:00+09:00")
        assertEquals(TimezoneOffset((9*60*60*1000).toDouble()), t2a.offset)
        assertEquals(11, t2a.hours)
        assertEquals("11:50", t2a.format("HH:mm"))
        assertEquals(1549507800000, t2a.utc.unixMillisLong)
```

**Comment by takahirom** [comment]
You help me every year😂😂I tagged this high priority!

**Comment by jmatsu** [comment]
That's from sessionize weird spec... :sad: let me add the timezone information to the api. I will get back here after fixing this, but i do not have time to work on this today, sorry.

**Comment by nukka123** [comment]
> let me add the timezone information to the api.

nice! 
But, be careful. If api fix first, `dateFormat.parse(startsAt)` will be throws Exception. 
We need tempolary workaround like as

```
            stime = try {
                stime = dateFormat.parse(startsAt).utc.unixMillisLong
            } catch () {
                DateFormat.FORMAT1.parse(startsAt).utc.unixMillisLong
            },
``

**Comment by jmatsu** [comment]
Good catch!
So... then how about adding `startsAtWIthTZ` and `endsAtWithTZ` as new fields? This does not affect the current behavior but would be able to realize what we want.

**Comment by amay077** [comment]
Good for we.

I will send PR what contains listed code:

```
private val dateFormat: DateFormat =
    DateFormat("yyyy-MM-dd'T'HH:mm:ssXXX")

private fun parseDateTime(dateText: String): DateTimeTz {
    val tz = "+09:00" // FIXME Should replace to timezone from API
    return dateFormat.parse("${dateText}${tz}")
}
```

If you added ``startsAtWithTZ `` and ``endsAtWithTZ `` then I will replace ``+09:00`` to it.

**Comment by takahirom** [comment]
Thanks 🙏

**Comment by amay077** [comment]
This issue has 2 sub-issues and almost fixed.

1. API returns datetime doesn't have timezone(+09:00) and logic uses UTC(+00:00), mismatch
-> fix to https://github.com/DroidKaigi/conference-app-2019/pull/354/commits/e952bd80a3ea65d3788fab36940949677a51c3db

2. View need convert timezone from data(UTC) to view(device)
-> fix to https://github.com/DroidKaigi/conference-app-2019/pull/354/commits/ef596ea0ed0272cd60502c1f693e9b1a0374eacb

Please merge PR #354 if you OK.

> If you added startsAtWithTZ and endsAtWithTZ then I will replace +09:00 to it.

I will continue to new PR.

**Comment by jmatsu** [comment]
I've added those TZ-aware fields to Session entities. Please check it out from https://droidkaigi2019-dev.appspot.com/api/timetable

**Comment by takahirom** [comment]
Now timezone is fixed as +9. But if we can use the app intentionally. So, I close this.

**Comment by amay077** [comment]
I think so too. Because DroidKaigi is domestic(+09:00) conf.
Thanks! :+1:
