### ISSUE TITLE
use Timber Mpp?

### ISSUE THREAD

**Issue by satoshun** [DroidKaigi/conference-app-2019#274]
## Overview (Required)

timber supports multi platform from 5.0.0-SNAPSHOT. How about using it?

pros
- Timber Android ecosystem is so large.
- Timber has a flexible API.

cons
- snapshot... not stable.
- iOS sample implements not exists in Timber project. So we must be implemented code for iOS Timber log.

## Links
- Timber: https://github.com/JakeWharton/timber
- SdkSearch: https://github.com/JakeWharton/SdkSearch

**Comment by takahirom** [comment]
I don't know that! I think that it is absolutely better than my implementation.

**Comment by satoshun** [comment]
thx reply! I think that it is better to look actual code. I make a PR 😃
