### ISSUE TITLE
Progress does not hide after reading session / セッション読み込み後にプログレスが非表示にならない

### ISSUE THREAD

**Issue by katsuki-nakatani** [DroidKaigi/conference-app-2019#275]
## Overview (Required)
アプリ起動直後のセッションを読み込んだあとにProgressが非表示にならない

一度アプリをBackgroundにしてから、再度Foreground(Resume)すると非表示になる
![screenshot_20190109-091328](https://user-images.githubusercontent.com/6699802/50867874-4dcefb80-13f0-11e9-9dab-70d66e75e63f.png)

**Comment by jmatsu** [comment]
Thank you for your report! We look forward to receiving the fix. :)

**Comment by takahirom** [comment]
Probably now it does not occur. I close this.
But If you have the same issue.
