### ISSUE TITLE
When open session/speaker detail from search result, Keyboard is not hidden

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#291]
## Overview (Required)
- title says everything
![image](https://user-images.githubusercontent.com/1386930/50878518-78ce4500-141a-11e9-8adf-7e09ff8abb3a.png)

**Comment by kaya5777** [comment]
🙋

**Comment by jmatsu** [comment]
Thank you and I overlooked your comment, sorry.
