### ISSUE TITLE
Session detail screen has a view which does not exist in gallery

### ISSUE THREAD

**Issue by NUmeroAndDev** [DroidKaigi/conference-app-2019#292]
## Overview (Required)
- EmojiTextView with id `session_message` does not exist in gallery.  
Is it okay to remove this?  

## Links
- https://github.com/DroidKaigi/conference-app-2019/blob/fd911fb18843ab31f08085d9f7ee131a3d82fea2/feature/session/src/main/res/layout/fragment_session_detail.xml#L297

**Comment by jmatsu** [comment]
Oh sorry, It's required.
For example, the view will appear when the room of the session will be changed.

**Comment by takahirom** [comment]
There is it 😄 
![image](https://user-images.githubusercontent.com/1386930/50878822-c8f9d700-141b-11e9-83b8-532c91ee1371.png)

**Comment by NUmeroAndDev** [comment]
@takahirom 
@jmatsu 

>For example, the view will appear when the room of the session will be changed.
>

I understood.

However, it is not implemented to set SessionMessage to EmojiTextView.
If it is not on the issue, will you create as soon as the design is decided?

**Comment by takahirom** [comment]
I found it here 👀 
https://github.com/DroidKaigi/conference-app-2019/blob/32e751c94c0135c93d9a5a5efa3f29f4fdbe3f01/feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/item/SpeechSessionItem.kt#L81

**Comment by NUmeroAndDev** [comment]
@takahirom 
Sorry, It is about the session detail screen 🙇

**Comment by takahirom** [comment]
Thanks 🙇

**Comment by takahirom** [comment]
Now it is added to the design 👍 
https://gallery.io/projects/MCHbtQVoQ2HCZd9Pbpex4PVP/files/MCHtA7U1iMGr6907YDmqSpau_jMZ_VsmeAE (Please open and request permission 🙏 )

**Comment by NUmeroAndDev** [comment]
🙋‍♂️
