### ISSUE TITLE
Unit test for AnnouncementActionCreator/AnnouncementStore

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#294]
## Overview (Required)
- You can try mockk like SessionContentsActionCreatorTest and SessionContentsStoreTest 👍 

## Links
- https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/session/src/test/java/io/github/droidkaigi/confsched2019/session/ui/actioncreator/SessionContentsActionCreatorTest.kt
- https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/session/src/test/java/io/github/droidkaigi/confsched2019/session/ui/store/SessionContentsStoreTest.kt

**Comment by keijumt** [comment]
🙋

**Comment by takahirom** [comment]
Thanks! Assigned 💯
