### ISSUE TITLE
Add firestore to .idea/dictionaries/dic.xml

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#295]
## Overview (Required)
-
![image](https://user-images.githubusercontent.com/1386930/50879435-3e66a700-141e-11e9-9af7-c65a64184a6c.png)

**Comment by NUmeroAndDev** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks 👍 Assigned 📘

**Comment by NUmeroAndDev** [comment]
@takahirom 

I do not see a warning in my AndroidStudio.

![screenshot](https://user-images.githubusercontent.com/13705006/50898369-535d2d80-1452-11e9-9f5b-c6fb2b5b27f8.png)

Has it already been fixed?

https://github.com/DroidKaigi/conference-app-2019/blob/31b53077ca2751c089762e284e6bcebf479c60be/.idea/dictionaries/dic.xml#L11

**Comment by takahirom** [comment]
It is not applied 🤔 
But.. thanks 🙇
