### ISSUE TITLE
Space between session tab

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#315]
## Overview (Required)
- 16dp space to here
![image](https://user-images.githubusercontent.com/1386930/50909759-db9dfb80-146f-11e9-9c3c-ba1bcce67f2e.png)

**Comment by sadashi-ota** [comment]
I'll take this one. :raised_hand:

**Comment by takahirom** [comment]
Thanks! I am looking forward to seeing what happens after implementation. 😄

**Comment by takahirom** [comment]
@sadashi-ota 
If you want to retry, Please do it. 🙏 
https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1ZL4CiG4FN1MxyTuSqZqU_xX_V5pDakCs%2Fnavtransitions-peer.mp4

**Comment by sadashi-ota** [comment]
Oh..., I'm sorry, I misunderstood.
I'll try again.
