### ISSUE TITLE
Add simultaneous interpretation(同時通訳) Filter

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#316]
## Overview (Required)
- I think "言語サポート"  Language support title. and tag name is "同時通訳" simultaneous interpretation
![image](https://user-images.githubusercontent.com/1386930/50909899-1b64e300-1470-11e9-9502-4ca6a24793cf.png)

**Comment by kazumax1218** [comment]
🙋‍♂️

**Comment by panpanini** [comment]
Thanks!! assigned 💯
