### ISSUE TITLE
Increase the SNS icon size

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#317]
## Overview (Required)
- Please expansion x 1.5
 
![image](https://user-images.githubusercontent.com/1386930/50910140-8a423c00-1470-11e9-8ea5-16bc9ef2ceb7.png)

**Comment by nano-nano** [comment]
✋️

**Comment by jmatsu** [comment]
Thank you so much. We look forward to seeing your PR.
