### ISSUE TITLE
Show Filtered(絞り込み中) to sessions title

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#318]
## Overview (Required)
- Use "絞り込む"  instead of "絞り込み中", When Filte is working.
Probably The English word is "Filtered". 
![image](https://user-images.githubusercontent.com/1386930/50910360-0046a300-1471-11e9-9404-97719d62d611.png)
![image](https://user-images.githubusercontent.com/1386930/50910434-1f453500-1471-11e9-85e8-264d8c834c35.png)

**Comment by NUmeroAndDev** [comment]
🙋‍♂️
