### ISSUE TITLE
Dashed line for session list

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#319]
## Overview (Required)
-
![image](https://user-images.githubusercontent.com/1386930/50910862-0426f500-1472-11e9-8c76-be9af8e66268.png)

## Links
- https://gallery.io/projects/MCHbtQVoQ2HCZd9Pbpex4PVP/files/MCHtA7U1iMGr6907YDmqSpaup_woDHhdXis (Please Open and Request permission)

**Comment by kawmra** [comment]
I wanna try this one 🙋
