### ISSUE TITLE
Add Intended Audience to session detail

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#320]
## Overview (Required)
- Add Intended Audience to session detail
- Session has intendedAudience: String field
design
![image](https://user-images.githubusercontent.com/1386930/50911353-0e95be80-1473-11e9-8f2d-ad80a39a1f1d.png)

## Links
- https://gallery.io/projects/MCHbtQVoQ2HCZd9Pbpex4PVP/files/MCHtA7U1iMGr6907YDmqSpau_jMZ_VsmeAE (Please open and request permission 🙏 )

**Comment by NUmeroAndDev** [comment]
🙋‍♂️ 

How do you translate `対象者`?

**Comment by jmatsu** [comment]
`Intended Audience` it is. 👍

**Comment by jmatsu** [comment]
Could you please handle this issue? Thanks.
