### ISSUE TITLE
Unexpected time text appears on session list when toggling fav status

### ISSUE THREAD

**Issue by kafumi** [DroidKaigi/conference-app-2019#324]
## Overview (Required)

- On session list, when changing session favorite status, unexpected time text can appear for a moment
- This issue can be always reproduced if
  - the time frame has multiple session AND
  - change favorite status of the session listed last in the time frame

![svid_20190109_223459_1](https://user-images.githubusercontent.com/12084705/50915589-2400ed80-145f-11e9-8cde-340e29a5ac4a.gif)

## Steps to reproduce

1. Launch app
2. On "Day1" session list, scroll to the "Unit test for ViewModel and LiveData" session
3. Click the favorite button of the session

## Expected behavior

- After step 3, there is no update about session time display

## Actual behavior

- After step 3, time text "11:20" appears on the left of the session even though another "11:20" text exists above

**Comment by takahirom** [comment]
Thanks!!!
