### ISSUE TITLE
Add forBeginners field to Session.SpeechSession in Session.kt from API

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#327]
## Overview (Required)
- Please add forBeginners field. It is used by the tag
- You don't need to modify UI

## Links
- Similer: https://github.com/DroidKaigi/conference-app-2019/pull/199/files
- API : https://droidkaigi2019-dev.appspot.com/api/timetable

**Comment by n-seki** [comment]
:raising_hand:

**Comment by jmatsu** [comment]
We assigned this issue to you, thanks. Please feel free to ask us if you have any questions.
