### ISSUE TITLE
Session tab animation

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#328]
## Overview (Required)
- Move the chip frame
- It's very exciting. (I do not know how to implement it 😉 )
https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1ZL4CiG4FN1MxyTuSqZqU_xX_V5pDakCs%2Fnavtransitions-peer.mp4

**Comment by NUmeroAndDev** [comment]
If it is only animation, it can be implemented only with TabLayout.
https://github.com/NUmeroAndDev/conference-app-2019/commit/3b7a44f1b90f04923865de6004a92d157ff2242a

<img src="https://user-images.githubusercontent.com/13705006/50952705-940d8300-14f4-11e9-82f5-6a3ecdc331c0.gif" width="45%">


I challenged Ripple to be the same as the link, but it was difficult. 😢

**Comment by takahirom** [comment]
`tabIndicator="@drawable/shape_pill_indicator"` 🆒
After merging, if you open Ripple effect issues, it seems to be better than ripple effect.
