### ISSUE TITLE
Keep scroll position when back from session detail

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#33]
# Overview
When back button press in session detail, scroll position will become top.
Because of BottomSheetDaySessionsFragment and BottomSheetFavoriteSessionsFragment instances are recreated.
If you know how to fix this, Please help me 🆘

**Comment by Akihiroooo** [comment]
I think I will challenge 🙋‍♂️ 
After checking the operation, it seems that savedInstanceState is null at the screen transition. When you rotate the screen, `savedInstanceState` exists.
I do not have confidence 😇

**Comment by Akihiroooo** [comment]
I thought, this seems to be a normal movement...

**Comment by takahirom** [comment]
If you can do it 🙏 
Should I assign you?

**Comment by Akihiroooo** [comment]
I'll do it 🙋‍♂️ 

> Should I assign you?
yes

**Comment by takahirom** [comment]
Thanks 👍 Assigned
