### ISSUE TITLE
Rename ic_settings_outline_black_24px to ic_settings_outline_black_24dp

### ISSUE THREAD

**Issue by tomoya0x00** [DroidKaigi/conference-app-2019#346]
## Overview (Required)
- We made a few mistakes in the file name 😢 
- `24px` is wrong. `24dp` is correct.

- current
`ic_settings_outline_black_24px`

- correct
`ic_settings_outline_black_24dp`

**Comment by tomoya0x00** [comment]
file path:
`/frontend/android/src/main/res/drawable/ic_settings_outline_black_24px.xml`

**Comment by devkudou** [comment]
🙋

**Comment by e10dokup** [comment]
@devkudou Thanks! Please grab this issue!
