### ISSUE TITLE
Add search sessions func / セッションの検索機能追加

### ISSUE THREAD

**Issue by kiuchikeisuke** [DroidKaigi/conference-app-2019#356]
## Overview (Required)
- Add search sessions function

## Links
- #179

**Comment by takahirom** [comment]
Sorry, What should we do for search sessions function? Now we can search session. 👀

**Comment by kiuchikeisuke** [comment]
Oh,Sorry, I was misunderstanding. 🙇 
When the search query was empty, I thought that the session was not searched because no sessions were added to the list.
Sessions were also searched after entering search queries!

**Comment by kiuchikeisuke** [comment]
I close it because I made a mistake
