### ISSUE TITLE
Add search session initial index / セッションのイニシャルインデックス追加

### ISSUE THREAD

**Issue by kiuchikeisuke** [DroidKaigi/conference-app-2019#357]
## Overview (Required)
- Add search session initial index

## image
Expect | Current
:--: | :--:
<img src="https://user-images.githubusercontent.com/1386930/51029206-08b9ed80-15d9-11e9-9211-2a5c593cb4ba.png" width="300" /> | <img src="https://user-images.githubusercontent.com/2305231/51072353-88f85580-16a2-11e9-8cf5-96bdaafcf39c.png" width="300" />

## Links
- #179

**Comment by takahirom** [comment]
Can you add an image for taking easy task? 🙏

**Comment by kiuchikeisuke** [comment]
@takahirom Of course! But I am sleepy so I will do it tomorrow.. 😴

**Comment by kiuchikeisuke** [comment]
@takahirom Added Image! (Is it Okey?)

**Comment by takahirom** [comment]
Thank you for adding images 🙇 🙇 
That design is here. (I thought you can screenshot in design page) 🙇 🙇 
Please use this image🙇 🙇 
https://gallery.io/projects/MCHbtQVoQ2HCZd9Pbpex4PVP/files/MCHtA7U1iMGr6-ZF5RXVf1KRWr8VHz3wbOk
![image](https://user-images.githubusercontent.com/1386930/51029206-08b9ed80-15d9-11e9-9211-2a5c593cb4ba.png)

**Comment by kiuchikeisuke** [comment]
@takahirom Image updated! 👍

**Comment by takahirom** [comment]
Probably we can implement that by adding logic here. Probably It's easy.
https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SearchFragment.kt#L123

**Comment by takahirom** [comment]
Thanks 👍 Assigned

**Comment by sugoi-wada** [comment]
Question. Should I change the place of this initial index char? Now It seems place the bottom of the first item.

**Comment by takahirom** [comment]
Probably yes.Sorry I don't notice it🙇

**Comment by sugoi-wada** [comment]
I found a way to solve this problem myself. Please check PR later.
