### ISSUE TITLE
Filter is not working to other tabs./他のタブに切り替えるとフィルターが機能していません。

### ISSUE THREAD

**Issue by kenz** [DroidKaigi/conference-app-2019#358]
## Overview (Required)
-
Set filter of sessions.フィルターを設定する。
![screenshot_20190111-015245](https://user-images.githubusercontent.com/479696/50983972-05285700-1544-11e9-9e2e-92562bd21656.png)

Switch to other tab and drop down the filter.別のタブに移動してフィルターを開く
Filter is set on the screen even now however it is not working. 画面上フィルターの設定は残っているが実際にはフィルターが機能していない。
![screenshot_20190111-015311](https://user-images.githubusercontent.com/479696/50983978-09547480-1544-11e9-9913-9acc30f0e823.png)

## Links
-

**Comment by takahirom** [comment]
Thanks! It is not a bug. It is Service Session like lunch so it is shown.
We want to solve this. But we should build complex logic. So currently we close this issue 🙇
