### ISSUE TITLE
Delete unneeded listener field

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#383]
## Kind (Required)

- Other

 ## Overview (Required)

- We can write it direct in listener.
 https://github.com/DroidKaigi/conference-app-2019/blob/795988ee4856bcaf47ecb50078452a514f6493a4/feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/item/SpeechSessionItem.kt#L53

**Comment by h3birth** [comment]
:raising_hand_man:

**Comment by takahirom** [comment]
Thanks assigned! 😴
