### ISSUE TITLE
Add Codelabs to filter target

### ISSUE THREAD

**Issue by tomoya0x00** [DroidKaigi/conference-app-2019#387]
## Kind (Required)

- Other

 ## Overview (Required)

- Currently, Codelabs is out of filter targets

- Add isFilterable property to [SessionType](https://github.com/DroidKaigi/conference-app-2019/blob/master/model/src/commonMain/kotlin/SessionType.kt) 
- Use the isFilterable property to determine if it is a filter target.

 ## Links	

- #231 
- #358

**Comment by kirimin** [comment]
I'll take this taks!!! ✋

**Comment by jmatsu** [comment]
Could you please handle this?
Thank you for your help in advance.
