### ISSUE TITLE
Fix ripple area for session tab

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#393]
## Kind (Required)

- Other

 ## Overview (Required)

Current
- ![image](https://user-images.githubusercontent.com/1386930/51070114-f09ca980-167e-11e9-85b5-e3616d91b12b.png)

What we want to do (only chip size)
https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1ZL4CiG4FN1MxyTuSqZqU_xX_V5pDakCs%2Fnavtransitions-peer.mp4

**Comment by matsujun** [comment]
🙋

**Comment by takahirom** [comment]
Thamks! Assigned🙏
