### ISSUE TITLE
Elevation when scroll session list

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#394]
## Kind (Required)

- Proposal / Discussion

 ## Overview (Required)

-  We want to add elevation like this. It's a very cool feature! 🆒 
![image](https://user-images.githubusercontent.com/1386930/51070209-ed0a2200-1680-11e9-9e87-938462ea1612.png)

 ## Links	
- https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1df7NTSaM4cVkrurAhFwKHqrZemqkcSAX%2Fcasestudies-crane-elevation.mp4
- https://material.io/design/material-studies/crane.html#layout

**Comment by piatekjulien** [comment]
Hello ! You're right, it would looks very good ✨ 
Can I be assigned to this? 😄

**Comment by takahirom** [comment]
Thanks!!! Assigned
