### ISSUE TITLE
iOS icon design needed!

### ISSUE THREAD

**Issue by kikuchy** [DroidKaigi/conference-app-2019#396]
## Kind (Required)

- Proposal / Discussion

 ## Overview (Required)

- A part of #132
- We need icon design for iOS app without Android Robot...!
    - Last year, I made https://github.com/kikuchy/DroidKaigi2018iOS and submit it for Apple.
    - Apple rejected this app because icon contains Android Robot picture... 😢

 ## Links	

- http://konifar.hatenablog.com/entry/2018/02/01/015601

**Comment by takahirom** [comment]
Probably we can do it with changing color and remove the horn of Android Robot.
https://itunes.apple.com/jp/app/droidkaigi-2018-flutter/id1341774412?mt=8
