### ISSUE TITLE
Display sessions without entering search queries / 検索画面でクエリ未入力でもセッションを表示する

### ISSUE THREAD

**Issue by kiuchikeisuke** [DroidKaigi/conference-app-2019#406]
## Kind (Required)
- Other(Enhance)

 ## Overview (Required)
- I think that it is better to display sessions without entering search queries
## image
Expect | Current
:--: | :--:
<img src="https://user-images.githubusercontent.com/1386930/51029206-08b9ed80-15d9-11e9-9211-2a5c593cb4ba.png" width="300" /> | <img src="https://user-images.githubusercontent.com/2305231/51072455-420b5f80-16a4-11e9-8752-37107aa31f65.png" width="300" />

 ## Links	
-

**Comment by kirimin** [comment]
Can I take this?

**Comment by takahirom** [comment]
Thanks! Assigned 🔍
