### ISSUE TITLE
Unneeded scrollbar is shown when switching tab

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#410]
## Kind (Required)

- Other

 ## Overview (Required)

- 
![image](https://user-images.githubusercontent.com/1386930/51073147-d4653080-16af-11e9-854f-0c3c785fee4f.png)

**Comment by kirimin** [comment]
May I take this?

**Comment by takahirom** [comment]
Thanks! Assigned 📜
