### ISSUE TITLE
Show toast when click entire survey

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#413]
## Kind (Required)

- Other

 ## Overview (Required)

- Show "not url decided" toast
- 
![image](https://user-images.githubusercontent.com/1386930/51073282-d7f9b700-16b1-11e9-8309-8a9d0b8caf09.png)

**Comment by akihito-okada** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks 👍 Assigned
