### ISSUE TITLE
Sponsor list screen is different from Gallery

### ISSUE THREAD

**Issue by NUmeroAndDev** [DroidKaigi/conference-app-2019#420]
## Kind (Required)

- Other

 ## Overview (Required)

The following items seem to be different.
- Card corner.
- Not divider.

Before | Current app
:--: | :--:
<img src="https://user-images.githubusercontent.com/13705006/51074790-9d4e4980-16c6-11e9-8905-6d9055cd6291.png" width="300" /> | <img src="https://user-images.githubusercontent.com/13705006/51074785-8b6ca680-16c6-11e9-81b6-a1e65b005335.png" width="300" />

**Comment by NUmeroAndDev** [comment]
I want to fix it. 🙋‍♂️ 
I want you to tell me, how do you think divider should create a Footer or add a flag to the Header?

**Comment by takahirom** [comment]
Thanks ! I assigned you 👍
