### ISSUE TITLE
Add "for beginners" tag

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#431]
## Kind (Required)

- Other

 ## Overview (Required)

- Please add "for beginners" tag like [this](https://github.com/DroidKaigi/conference-app-2019/pull/265/files#diff-dcfc19806538809dc2fdb8a4008236b5R182)
- Now we can use the session field `forBeginners`. It's Japanese text is "初心者向け"
[forBeginners](https://github.com/DroidKaigi/conference-app-2019/blob/master/model/src/commonMain/kotlin/Session.kt#L33)

 ## Links	

- https://github.com/DroidKaigi/conference-app-2019/pull/265

**Comment by sekiya9311** [comment]
🙋

**Comment by takahirom** [comment]
Thanks! Assigned! 
You take this issue very fast 🏎
