### ISSUE TITLE
Add a session filter which allows users to see only level sessions

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#432]
## Kind (Required)

- Other

 ## Overview (Required)

- Add a filter that ｀Beginners｀ and ｀Intermediates/Expert｀ chip tags and that title is `Level`.
- Please put `Level` filter after simultaneous interpretation filter.
- You can use [forBeginners](https://github.com/DroidKaigi/conference-app-2019/blob/master/model/src/commonMain/kotlin/Session.kt#L33)

 ## Links	

- https://github.com/DroidKaigi/conference-app-2019/pull/429

**Comment by kirimin** [comment]
I want to try to this one. ✋

**Comment by takahirom** [comment]
Thanks! Assigned 🎚

**Comment by kirimin** [comment]
@takahirom 
>Add a filter that ｀Beginners｀ and ｀Intermediates/Expert｀ chip tags and that title is Level.

Do ｀Beginners｀ and ｀Intermediates/Expert｀ texts should translate?

**Comment by takahirom** [comment]
Sorry Please use this 🙏 

｀Audience Category｀ -> ｀Beginners｀, ｀Unspecified｀
｀受講者カテゴリ｀ -> ｀初心者歓迎｀, ｀指定無し｀

**Comment by kirimin** [comment]
Thanks!!!

**Comment by kirimin** [comment]
Other filter titles are seems not translated.
does Audience Category need to translate?

```xml
    <string name="session_filter_room" translatable="false">Room</string>
    <string name="session_filter_language" translatable="false">Language</string>
    <string name="session_filter_language_support" translatable="false">Language Support</string>
    <string name="session_filter_audience_category" translatable="false">Audience Category</string>
    <string name="session_filter_category" translatable="false">Category</string>
    <string name="session_detail_intended_audience">Intended Audience</string>
```
