### ISSUE TITLE
Disable Crashlytics if the apk has been built on the local environment

### ISSUE THREAD

**Issue by jmatsu** [DroidKaigi/conference-app-2019#433]
## Kind (Required)

- New feature

 ## Overview (Required)

- The current Crashlytics setting is enabled in every environment including CI, your PC, and my PC. However, we should collect only crashes from apks which have been built on CI.
- `isCI` flag is available in build.gradle, and it will be true only on CI environment.

 ## Links	

-

**Comment by akihito-okada** [comment]
I want to try to this one. ✋
