### ISSUE TITLE
Some of session titles don't be English

### ISSUE THREAD

**Issue by clockvoid** [DroidKaigi/conference-app-2019#445]
## Kind (Required)

- report

 ## Overview (Required)

- some of the session titles like "ウェルカムトーク" or "ランチ"
![[Imgur](https://i.imgur.com/AJkG6APm.png)](https://i.imgur.com/AJkG6AP.png)

I know there is a PR to support English (#171).
I researched this PR's version, too.

![[Imgur](https://i.imgur.com/cUX2c7om.png)](https://i.imgur.com/cUX2c7o.png)

It's Japanese...

I tested two different versions: Asus Zenfone4, Android 8.1 and Nexus 5X, Android 9.0. All of these environments encountered the issue.

I think it's not an app side issue. (I mean, it's server side.) I think it does not suit here, but I don't know the correct place and I report here.
Please check it out.

 ## Links	

-

**Comment by takahirom** [comment]
The app can fix this issue. We can use englishTitle here.
https://github.com/DroidKaigi/conference-app-2019/blob/master/data/repository-impl/src/main/java/io/github/droidkaigi/confsched2019/data/repository/mapper/SessionMappers.kt#L26

**Comment by clockvoid** [comment]
Thank you for that fast reply.
I'm gonna try to fix it.
Is your phone free to this issue?

**Comment by takahirom** [comment]
My phone has the same issue😥
Thanks. Assigned
