### ISSUE TITLE
Scroll to LIVE when Day1/Day2 secondary tapped

### ISSUE THREAD

**Issue by amay077** [DroidKaigi/conference-app-2019#446]
## Kind (Required)

- Proposal / Discussion

 ## Overview (Required)

- In Timeline page, scroll to current session when Day1(or Day2) button's secondary tapped
- Like DroidKaigi 2018 apps

 ## Links	

- https://github.com/DroidKaigi/conference-app-2018/issues/343

**Comment by takahirom** [comment]
I think this is useful! Thanks 👍

**Comment by nacatl** [comment]
Can I challenge it?
(If the #434 will conflict this, I stop the challenge.)

**Comment by takahirom** [comment]
Probably it will be a conflict. But perhaps the code that conflicts is around the scroll, so I think you can do it. 👍

**Comment by nacatl** [comment]
I'm sorry for I'm late...
