### ISSUE TITLE
Show session list for iOS app

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#451]
## Kind (Required)
- Proposal / Discussion

 ## Overview (Required)

- You can open Xcode project by opening frontend/ios

- We can use session data. Please show it.
![image](https://user-images.githubusercontent.com/1386930/51097043-7ac24a80-1804-11e9-93a0-04493fd423db.png)

- I think It is enough to display session in one line.
- If you want to use library like RxSwift, please use it.

**Comment by akira108** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thank you! Assigned! 👍
