### ISSUE TITLE
announcement item title text cut off when large font size

### ISSUE THREAD

**Issue by yamacraft** [DroidKaigi/conference-app-2019#459]
## Kind (Required)

- Other

 ## Overview (Required)

- announcement item title text cut off when large font size for system

![2019-01-14 12 12 35](https://user-images.githubusercontent.com/1332886/51100513-caf7d780-1819-11e9-97c4-26a3df53e366.png)

**Comment by takahirom** [comment]
Nice catch 👍

**Comment by yamacraft** [comment]
i fix it. ✋

**Comment by takahirom** [comment]
Thanks! Assigned
