### ISSUE TITLE
When empty MyPlan, Hide session header

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#463]
## Kind (Required)

- Other

 ## Overview (Required)

- 
![image](https://user-images.githubusercontent.com/1386930/51103566-9b9b9780-1826-11e9-96d0-0919d2465c04.png)

**Comment by NUmeroAndDev** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned🔖
