### ISSUE TITLE
Support Android Studio 3.3

### ISSUE THREAD

**Issue by panpanini** [DroidKaigi/conference-app-2019#471]
## Kind (Required)

Android Studio 3.3 is now released on the stable track, so we should also support build tools version 3.3 🎉 

 ## Overview (Required)

- update `Dep.kt#GradlePlugin#android` to version `3.3.0` 
- check for any build failures or unexpected crashes

 ## Links	

- https://developer.android.com/studio/releases/

**Comment by NUmeroAndDev** [comment]
🙋‍♂️

**Comment by panpanini** [comment]
Thanks! Assigned

**Comment by NUmeroAndDev** [comment]
Help me!!

Updated `com.android.tools.build:gradle` to 3.3, so needs to be `gradle-4.10.1-all.zip`.
Then I faced a problem that the build did not pass.

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':model:linkReleaseFrameworkIOS'.
> Could not resolve all task dependencies for configuration ':model:iOSCompileKlibraries'.
   > Could not resolve com.soywiz:klock:1.0.0.
     Required by:
         project :model
      > Could not resolve com.soywiz:klock:1.0.0.
         > Could not parse module metadata https://dl.bintray.com/soywiz/soywiz/com/soywiz/klock/1.0.0/klock-1.0.0.module
            > Unsupported format version '0.3' specified in module metadata. This version of Gradle supports format version 0.4 only.
```

Downgraded with # 81, but is there any solution?

**Comment by panpanini** [comment]
👀 let me have a look

**Comment by takahirom** [comment]
Kotlinx and Klock depend on Metadata before Gradle 4.7 and Android Studio 3.3 does not work unless it is Gradle 4.10.1.
I don't have solution😭

**Comment by NUmeroAndDev** [comment]
This solution is difficult for me, so if you need it you can remove me from the assignment. 🙇

**Comment by panpanini** [comment]
😭 it looks like maybe its harder than I thought at first.. sorry 🙏

**Comment by Pluu** [comment]
It seems that the issue has not been solved yet.
https://github.com/Kotlin/kotlinx.coroutines/issues/564
https://github.com/korlibs/klock/issues/16

**Comment by Pluu** [comment]
Related issues are registered.
I registered in the comment for reference.
- https://youtrack.jetbrains.com/issue/KT-29045
- https://twitter.com/_yshrsmz/status/1085027892117958656

**Comment by Pluu** [comment]
The klock maker has been successful with builds based on Kotlin 1.3.20 and Gradle 5.1.1, and announced the availability of a temporary version.
https://github.com/korlibs/klock/issues/16
