### ISSUE TITLE
The title of the session list and the favorite button are covered.

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#473]
## Kind (Required)

- Other

 ## Overview (Required)

- 
![image](https://user-images.githubusercontent.com/1386930/51155429-d0f1c500-18ba-11e9-81a7-9ccc7acb3cd2.png)

**Comment by NUmeroAndDev** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Too fast 🏎 
Thanks! Assigned
