### ISSUE TITLE
About screen app version is not correct app version

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#476]
## Kind (Required)

- Other

 ## Overview (Required)

- It is not the app version. just strings.xml
- We should Add app version to versions.kts and use it in about/build.gradle 

 ## Links	

- https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/about/src/main/res/values/strings.xml#L12

**Comment by kirimin** [comment]
I'll take this one ✋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
