### ISSUE TITLE
Session list favorite button touch feedback or animation

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#477]
## Kind (Required)

- Other

 ## Overview (Required)

- We should add touch feedback. Ripple? Animation?

**Comment by sobaya-0141** [comment]
Rippleを付ける対応でよければ対応します 。
stateListAnimatorでアニメーションさせようと思ったのですが、上手くいかなくて。。。

**Comment by takahirom** [comment]
It seems better than the current implementation 👍
