### ISSUE TITLE
Add contentDescription to floorMapImage

### ISSUE THREAD

**Issue by tomoya0x00** [DroidKaigi/conference-app-2019#480]
## Kind (Required)

- Other

 ## Overview (Required)

- floorMapImage has not contentDescription

 ## Links	

- https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/floormap/src/main/res/layout/item_floor_map.xml#L22

**Comment by masaibar** [comment]
✋

**Comment by takahirom** [comment]
Thanks! Assigned 👍

**Comment by masaibar** [comment]
@tomoya0x00 @takahirom Should I include the floor number in the contentDescription?

**Comment by takahirom** [comment]
It seems better to have it.
