### ISSUE TITLE
Fix sample data of announcement

### ISSUE THREAD

**Issue by tomoya0x00** [DroidKaigi/conference-app-2019#482]
## Kind (Required)

- Other

 ## Overview (Required)

- Add comma to end of line

 ## Links	

- https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/announcement/sampledata/announcement.json#L2

**Comment by k-masashi** [comment]
✋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
