### ISSUE TITLE
Fix directory path to package name

### ISSUE THREAD

**Issue by tomoya0x00** [DroidKaigi/conference-app-2019#483]
## Kind (Required)

- Other

 ## Overview (Required)

- Title say everything!

 ## Links	

- https://github.com/DroidKaigi/conference-app-2019/blob/master/data/api/src/test/java/io/github/droidkaigi/confsched2019/ui/ExampleUnitTest.java
- https://github.com/DroidKaigi/conference-app-2019/blob/master/data/db/src/test/java/io/github/droidkaigi/confsched2019/ui/ExampleUnitTest.java
- https://github.com/DroidKaigi/conference-app-2019/blob/master/data/firestore/src/test/java/io/github/droidkaigi/confsched2019/ui/ExampleUnitTest.java
- https://github.com/DroidKaigi/conference-app-2019/blob/master/data/repository/src/test/java/io/github/droidkaigi/confsched2019/ui/ExampleUnitTest.java
- https://github.com/DroidKaigi/conference-app-2019/blob/master/ext/log/src/test/java/io/github/droidkaigi/confsched2019/ui/ExampleUnitTest.java

**Comment by katsuki-nakatani** [comment]
✋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
