### ISSUE TITLE
Fix package name of FirestoreComponent.kt

### ISSUE THREAD

**Issue by tomoya0x00** [DroidKaigi/conference-app-2019#484]
## Kind (Required)

- Other

 ## Overview (Required)

- Title say everything
- `package io.github.droidkaigi.confsched2019.data.repository` is wrong

 ## Links	

- https://github.com/DroidKaigi/conference-app-2019/blob/master/data/firestore-impl/src/main/java/io/github/droidkaigi/confsched2019/data/firestore/FirestoreComponent.kt

**Comment by beta1139** [comment]
✋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
