### ISSUE TITLE
Add error callback for iOS in common module

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#493]
## Kind (Required)

- Proposal / Discussion

 ## Overview (Required)

- We should add error callback for iOS
- We can use `try catch` for `suspend function` and call callback.

 ## Links	

- https://github.com/DroidKaigi/conference-app-2019/blob/master/data/api-impl/src/commonMain/kotlin/io/github/droidkaigi/confsched2019/data/api/KtorDroidKaigiApi.kt#L39

**Comment by amay077** [comment]
✋

Ok, I'm ready for Kotlin MPP 👍

**Comment by ymnder** [comment]
Thanks! Assigned :)
