### ISSUE TITLE
Fix item decoration for session time

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#51]
## Overview (Required)
- current
![decoration](https://user-images.githubusercontent.com/5106629/50737273-7ac1b980-120a-11e9-9d97-ec6679f2ff01.gif)
 - Instead of disappearing when scrolling up, push out.
![iosched2018](https://user-images.githubusercontent.com/5106629/50737295-c7a59000-120a-11e9-9de3-2415ac4961f5.gif)

**Comment by kafumi** [comment]
Could I try this issue? 🙋‍♂️

**Comment by jmatsu** [comment]
Yes, of course! 😄 
We assigned this issue to you. Thanks!

**Comment by kafumi** [comment]
Thank you for the prompt response!
