### ISSUE TITLE
Show Toast message if toggle session favarite fail

### ISSUE THREAD

**Issue by futabooo** [DroidKaigi/conference-app-2019#513]
## Kind (Required)

- Other

 ## Overview (Required)

- if toggle session favarite fail, no feedback for user
- add feedback message

 ## Links	

- https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/actioncreator/SessionContentsActionCreator.kt#L74

**Comment by takahirom** [comment]
How about using snackbar?
My recommendation is to have snackbarmessage etc in the system store and observe it by MainActivity.

**Comment by futabooo** [comment]
I agree with you!

**Comment by kirimin** [comment]
Can I take this task?

**Comment by takahirom** [comment]
Thanks! Assigned👍
