### ISSUE TITLE
Apply font design in session detail

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#514]
## Kind (Required)

- Other

 ## Overview (Required)

- If the text can contain Japanese text, please use Noto Sans Font, otherwise please use Lekton.
(Japanese: もしそのTextが日本語の文を含みえるのであれば、fontをNoto Sansにして、それ以外をLektonにする)

 ## Links	

- Sorry, The design of the current Gallery is wrong 🙇 
![image](https://user-images.githubusercontent.com/1386930/51381442-82148b80-1b57-11e9-832a-92d3cbd25c03.png)

**Comment by daisukemotonami** [comment]
✋🏽

**Comment by satsukies** [comment]
Thanks! Assigned!

**Comment by takahirom** [comment]
Can you access here? If not, please request.
https://gallery.io/projects/MCHbtQVoQ2HCZd9Pbpex4PVP/files/MCHtA7U1iMGr60CQdbvgFMCPHe-6adOX1IM
Probably You can confirm font weight. Please consider and select it. 🙇

**Comment by daisukemotonami** [comment]
I requested it

**Comment by takahirom** [comment]
Sorry, I can not receive the request 🙇 
Can you tell me your email address?
If you send to this email address takam.dev@gmail.com. I will send a request to you 🙏
