### ISSUE TITLE
Use WorkManager for FCM topic subscription

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#516]
## Kind (Required)

- Other

 ## Overview (Required)

- We can use WorkManager instead of intent service 
- You can use with Coroutine, Exponential Backoff, Add restrictions on the Internet.

 ## Links	

- https://github.com/DroidKaigi/conference-app-2019/blob/156f474534984b56472dfbaf48137bfb0ce6ca52/feature/notification/src/main/java/io/github/droidkaigi/confsched2019/notification/service/ManageTopicSubscriptionIntentService.kt

**Comment by panpanini** [comment]
@kirimin How's your progress on this~? Is there something we can help you with? 🕵️‍♀️

**Comment by kirimin** [comment]
@panpanini I'm so sorry for this. 🙏 
I don't begin this task yet because of my business work and personal illness...
I think I should release this task to other contributors for don't late to the conference. 😢

**Comment by panpanini** [comment]
Oh that's unfortunate... I hope you feel better soon! I'll unassign you for now then

**Comment by geckour** [comment]
Can I try this ? 🙋

**Comment by takahirom** [comment]
Thank you for challenging this issue!

**Comment by geckour** [comment]
I have one more question...
If Worker uses Exponential Backoff, does it still needs limitation of retry times (currently set max to 3)?

**Comment by jmatsu** [comment]
I guess that's also needless. The previous *3* was just an experimental value. 👍

**Comment by geckour** [comment]
@jmatsu Thanks!
