### ISSUE TITLE
Create empty screen Fragment and layout for tabular form sessions

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#518]
## Kind (Required)

- Other

 ## Overview (Required)

- Add item here and please create empty fragment and layout
![image](https://user-images.githubusercontent.com/1386930/51384205-f69ef880-1b5e-11e9-9ce5-7634c0d1045c.png)

 ## Links	

- https://github.com/DroidKaigi/conference-app-2019/issues/150

**Comment by clockvoid** [comment]
I want to try it !

**Comment by takahirom** [comment]
Thanks! Assigned 🙏

**Comment by clockvoid** [comment]
Does this feature have pager like session pages screen?
Or that has just one page and the timetable includes both of days?

If that has tab layout, I can add tabbed and empty layout file for the item.

**Comment by tomoya0x00** [comment]
@clockvoid Sorry, we might need to consider this 🙇 
We will get back here after having a talk with designer.

Thanks!

**Comment by takahirom** [comment]
@clockvoid 

> I can add tabbed and empty layout file for the item.

Sorry for late. I talk to a designer. Please do it 👍

**Comment by clockvoid** [comment]
I'm sorry for late to notice.
I will.

**Comment by clockvoid** [comment]
Does it seem ok?
![Imgur](http://i.imgur.com/pPNbPvL.jpg)
![Imgur](http://i.imgur.com/iUiVuD8.jpg)

**Comment by takahirom** [comment]
Thanks! LGTM!
