### ISSUE TITLE
Use iosched2018 chip animation

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#52]
## Overview (Required)
-
![chip_now](https://user-images.githubusercontent.com/1386930/49684547-8b521780-fb18-11e8-9de4-f4b259e4ca72.gif)
↓
![chip_google](https://user-images.githubusercontent.com/1386930/49684564-bdfc1000-fb18-11e8-9d37-e6f4950a74fb.gif)

## Links
- https://github.com/google/iosched/blob/d8bc48b20c132b519879eda3a8e9af120519e159/mobile/src/main/java/com/google/samples/apps/iosched/ui/schedule/filters/EventFilterView.kt

**Comment by kafumi** [comment]
Could I try this issue? ✋

Also, if there are some design spec or color guide of this app which can help implementing these chips, I'd like to see. Is such material available? (I guess it's not, though)

**Comment by takahirom** [comment]
Thank you for tackling this issue 👍 

> (I guess it's not, though)

Exactly.
If you can wait for one week, we probably some spec 🤔 (Designer is busy 😭 )

**Comment by kafumi** [comment]
I can understand the situation... In that case, is it okay to try implementing the chip behavior with tentative simple colors (e.g. red, white, and black) first? I think I need time to investigate if it's possible to achieve the animation with standard `Chip`s or I need custom view with low-level canvas drawing as in iosched.

**Comment by takahirom** [comment]
I think we should use the custom view. But If you can do it. Please do it.
I think like this 👀 

* text
↑white dot
   ↑ text color:white    background:red

text x
↑ text color:black    background:white

**Comment by takahirom** [comment]
Assigned 🙏

**Comment by kafumi** [comment]
Thank you for the assignment. I've read the code of `Chip` & `ChipDrawable` and just found it's impossible to implement animation with it 😇Will create custom view.

Regarding coloring, I thought exactly what you suggest. It's clear. Thank you!

**Comment by takahirom** [comment]
We are waiting for your PR 🙌

**Comment by kafumi** [comment]
I've implemented the animated chips with simple colors on #287. I didn't make #287 to close this #52 because we still need to apply colors to the chips after such design direction comes out.

However, it might be better to track the remaining task as another issue. If you think so too, please close this one.

**Comment by takahirom** [comment]
Thanks! Designers will decide the color. We can create that time
