### ISSUE TITLE
Remove left space of service sessions in search screen

### ISSUE THREAD

**Issue by matsujun** [DroidKaigi/conference-app-2019#526]
## Kind (Required)

- Other

 ## Overview (Required)

- Remove this space
<img src="https://user-images.githubusercontent.com/10704349/51401176-7f348d80-1b8d-11e9-9f84-2d455a07238b.png" width="300" />

 ## Links	

-

**Comment by NUmeroAndDev** [comment]
🙋‍♂️

**Comment by tomoya0x00** [comment]
Thanks! Assigned🙏
