### ISSUE TITLE
Improve floor map screen

### ISSUE THREAD

**Issue by tomoya0x00** [DroidKaigi/conference-app-2019#527]
## Kind (Required)

- Other

 ## Overview (Required)

- Occurs IllegalArgumentException in floor map( #523 )
- Can not scroll after zooming the floor map
- Delete wasted space above and below the floor map
![screenshot_20190119-013817](https://user-images.githubusercontent.com/5106629/51401788-08988f80-1b8f-11e9-87cf-7c5a3e70daab.png)
![screenshot_20190119-013840](https://user-images.githubusercontent.com/5106629/51401798-0b938000-1b8f-11e9-8e83-9d376c5d916a.png)

 ## Links	

none

**Comment by clockvoid** [comment]
I suggest you a new behavior:

1. when open floor map, the image is original size
2. then, the user can zoom the image and scroll horizontally and vertically.
3. when maximam scrolling, move tab.

like the screenshot below:
![droidkaigi](https://user-images.githubusercontent.com/6965122/51421424-87b6b380-1be1-11e9-952b-ea9adb0f227b.gif)

**Comment by tomoya0x00** [comment]
@clockvoid Looks great! 🆒 

May we assign this issue to you?

**Comment by clockvoid** [comment]
Off course yes.

**Comment by tomoya0x00** [comment]
Thanks😁 Assigned!

**Comment by clockvoid** [comment]
By the way, the app does not support English floor map.
Additionally, in the floor map photo, Elevator icon explains Smoking space...

Is the image of the floor map tentative?

**Comment by tomoya0x00** [comment]
@clockvoid Thank you for sharing your notice 🙇 

> Is the image of the floor map tentative?

Yes!
We will fix those problems in #385 💪

**Comment by clockvoid** [comment]
Oh, I see.
I'm sorry, I had been overlooked.
