### ISSUE TITLE
Sort sessions in search screen

### ISSUE THREAD

**Issue by matsujun** [DroidKaigi/conference-app-2019#528]
## Kind (Required)

- Other

 ## Overview (Required)

- Speakers are sorted, but sessions are not sorted. Please sort them.

Current behavior is ... 😢 
<img src="https://user-images.githubusercontent.com/10704349/51402139-ff5bf280-1b8f-11e9-9a7b-e90be25de3ff.png" width="300"/>

 ## Links	

-

**Comment by nakasho-dev** [comment]
✋🏽

**Comment by tomoya0x00** [comment]
Thanks! Assigned 👍
