### ISSUE TITLE
Add section title to SearchFragment

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#529]
## Kind (Required)

- Other

 ## Overview (Required)

- Add section title to SearchFragment
- If you tell me email adress (or inviting to GitHub bio email adress), I will send invitation of Gallery.

![image](https://user-images.githubusercontent.com/1386930/51402811-e94f3180-1b91-11e9-8306-f5f5a14dbc8e.png)

 ## Links	

-https://gallery.io/projects/MCHbtQVoQ2HCZd9Pbpex4PVP/files/MCHtA7U1iMGr6-ZF5RXVf1KRWr8VHz3wbOk

**Comment by a25max** [comment]
🙋

**Comment by tomoya0x00** [comment]
Thanks! Assigned😁
