### ISSUE TITLE
Add search section divider

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#530]
## Kind (Required)

- Other

 ## Overview (Required)

- 
![image](https://user-images.githubusercontent.com/1386930/51403053-a2ae0700-1b92-11e9-9e35-98c0f1351843.png)

 ## Links	

-  We can use this
https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/sponsor/src/main/java/io/github/droidkaigi/confsched2019/sponsor/ui/item/DividerItem.kt

**Comment by NUmeroAndDev** [comment]
🙋‍♂️

**Comment by tomoya0x00** [comment]
Thank you always! Assigned😊
