### ISSUE TITLE
Apply tag color for category

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#541]
## Kind (Required)

- Other

 ## Overview (Required)

- 
![image](https://user-images.githubusercontent.com/1386930/51425535-8c4e8c80-1c20-11e9-8b47-a48db637f84c.png)

no | category | background | textcolor
-- | -- | -- | --
1 | UI・デザイン (UI and Design) | #E5E8EA | #353435
2 | アプリアーキテクチャ (Designing App Architecture) | #E5E8EA | #353435
3 | Androidプラットフォーム (Android Platforms) | #E5E8EA | #353435
4 | 保守・運用・テスト (Maintenance Operations and Testing) | #E5E8EA | #353435
5 | 開発体制 (Development processes) | #E5E8EA | #353435
6 | Android FrameworkとJetpack(Support Library) (Android Framework and Jetpack (a.k.a. Support Library)) | #E5E8EA | #353435
7 | 開発ツール (Productivity and Tools) | #E5E8EA | #353435
8 | クロスプラットフォーム (Cross-platform Development) | #E5E8EA | #353435
9 | xR, | #E5E8EA | #353435
10 | セキュリティ (Security), | #E5E8EA | #353435
11 | ハードウェア (Hardware) | #E5E8EA | #353435
12 | その他 (Other) | #E5E8EA | #353435
  |   |   |  
A | 日本語 | #FDD7D4 | #F63529
B | 英語 | #E8E6F3 | #190089
  |   |   |  
  | 初心者歓迎 | #C1EBDD | #00BE80
  | ルーム | #D8D7DC | #353435

 ## Links	

-

**Comment by kafumi** [comment]
@takahirom Are the slightly different text colors of categories described above are intended? According to Gallery, #353435 is the common text color for all categories 🤔

**Comment by takahirom** [comment]
I just notice it. Probably it is a mistake by using a spreadsheet 😄 
![image](https://user-images.githubusercontent.com/1386930/51426571-f1f64500-1c2f-11e9-9ee7-6993806d4990.png)

**Comment by NUmeroAndDev** [comment]
I want try it. 🙋‍♂️

**Comment by takahirom** [comment]
thank you always 👍
