### ISSUE TITLE
Apply filter design

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#542]
## Kind (Required)

- Other

 ## Overview (Required)

- 
![image](https://user-images.githubusercontent.com/1386930/51425510-47c2f100-1c20-11e9-844e-2c4366f26524.png)

 ## Links	

- If you tell me email adress (or inviting to GitHub bio email adress), I will send invitation of Gallery.
 https://gallery.io/projects/MCHbtQVoQ2HCZd9Pbpex4PVP/files/MCHtA7U1iMGr60CQdbvgFMCPx3QUr8d0FOc

**Comment by kafumi** [comment]
Could I try this issue? 🙋‍♂️

**Comment by takahirom** [comment]
@kafumi Can you access Gallery? If not, please mail to takam.dev@gmail.com for the invitation 🙏

**Comment by kafumi** [comment]
@takahirom Thank you. I've sent an email to your address above 🙏

**Comment by takahirom** [comment]
@kafumi I sent the invitation 👍

**Comment by kafumi** [comment]
Thank you! I've successfully see the Gallery. I understand the followings are the major tasks we need to do.

- Apply Lekton typeface to the texts
- Change the colors
- Remove small close icon which is shown when filter is activated

If it's okay, please let me take this issue :bow:

**Comment by takahirom** [comment]
> Apply Lekton typeface to the texts
Change the colors

YES 🙏 

Currently, font policy is this.

If the text can contain Japanese text, please use Noto Sans Font, otherwise please use Lekton.
(Japanese: もしそのTextが日本語の文を含みえるのであれば、fontをNoto Sansにして、それ以外をLektonにする)

Sorry, Can you wait for this `Remove small close icon` 🙏

**Comment by takahirom** [comment]
Please do not delete small close icon 🙏

**Comment by kafumi** [comment]
Thank you, I understand the font policy and that the close icons need to be kept.

I have one question regarding typeface. Should we use Lekton to category filter texts in English preference? Or, is it to use Noto Sans Font for category filters regardless of language preferences? I ask this because whether the texts of category filters contain Japanese or not depends on language preference.

**Comment by kafumi** [comment]
Okay, let me see... But maybe I will use Lekton only for Room filter texts for now...

**Comment by kafumi** [comment]
I'm sorry for being late. I will create a PR between 7PM - 8PM later 🙇

**Comment by takahirom** [comment]
There is no need to panic. This is necessary for release, but it is okay if it is late. 🙏
