### ISSUE TITLE
Remove unneeded dashed line between day1 to day2 in MyPlan

### ISSUE THREAD

**Issue by tomoya0x00** [DroidKaigi/conference-app-2019#546]
## Kind (Required)

- Other

 ## Overview (Required)

- Remove dashed line between last session of day1 to first session of day2 in MyPlan
- current
![device-2019-01-19-221020](https://user-images.githubusercontent.com/5106629/51428684-c3856380-1c49-11e9-882c-d54781e5457b.png)

 ## Links	

- none

**Comment by sekiya9311** [comment]
🙋‍♂️
