### ISSUE TITLE
Delete speaker screen speaker title

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#553]
## Kind (Required)

- Other

 ## Overview (Required)

- 
![image](https://user-images.githubusercontent.com/1386930/51435654-94a9d480-1cbf-11e9-8a32-7657cbf3b886.png)

**Comment by kouhon** [comment]
✋

**Comment by takahirom** [comment]
Thanks! Assigned 👍

**Comment by kouhon** [comment]
ok 👌
