### ISSUE TITLE
Add commit number to About DroidKaigi screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#554]
## Kind (Required)

- Other

 ## Overview (Required)

- Please show it like this 1.0.0 (189ab19)
![image](https://user-images.githubusercontent.com/1386930/51435706-53b2bf80-1cc1-11e9-8474-d44bcb5660ff.png)

**Comment by tjmmm** [comment]
✋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
