### ISSUE TITLE
Apply session list item design for iOS App

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#560]
## Kind (Required)

- Proposal / Discussion

 ## Overview (Required)

- You do not have to work hard. Only show information.
![image](https://user-images.githubusercontent.com/1386930/51437318-0db92400-1ce0-11e9-9d91-44d1237e5f07.png)
![image](https://user-images.githubusercontent.com/1386930/51437291-9aafad80-1cdf-11e9-9b38-531798626573.png)
- An implementation where time sticks up, display of speaker and favorite and tag colors are unnecessary.
- Design spec does not exit. Please do your best 🙏 

## link
You can build iOS App in this step.
https://github.com/DroidKaigi/conference-app-2019/tree/master/frontend/ios

**Comment by ShoMasegi** [comment]
I want to try this 🙋‍♂️

**Comment by ShoMasegi** [comment]
@satsukies I want to watch this app design of android. would you invite me to Gallery?🙇‍♂️

**Comment by takahirom** [comment]
Sorry, Please wait 🙏

**Comment by takahirom** [comment]
Can you email to takam.dev@gmail.com . I want to send an invitation to the Gallery.

**Comment by ShoMasegi** [comment]
@takahirom I sent email just now! 🙆‍♂️Thanks!!

**Comment by takahirom** [comment]
@ShoMasegi I sent invitation!🙏

**Comment by takahirom** [comment]
You can look tag colors here
https://github.com/DroidKaigi/conference-app-2019/issues/541
