### ISSUE TITLE
Show speaker in Session list for iOS App

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#561]
## Kind (Required)

- Proposal / Discussion

 ## Overview (Required)

- Design spec does not exist. Please do your best 🙏 
- There may be more than one speaker for the session.
![image](https://user-images.githubusercontent.com/1386930/51437334-6dafca80-1ce0-11e9-8d72-3adfecf9848b.png)

## link
You can build iOS App in this step.
https://github.com/DroidKaigi/conference-app-2019/tree/master/frontend/ios

**Comment by takasfz** [comment]
It seems already implemented with #583 :eyes:

**Comment by takahirom** [comment]
Thanks
