### ISSUE TITLE
Session detail screen for iOS App

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#562]
## Kind (Required)

- Other

 ## Overview (Required)

- Design spec does not exist. Please do your best 🙏
- You don't need to implement bottom app bar.
- Please just show session details 🙏 

![image](https://user-images.githubusercontent.com/1386930/51437377-e1ea6e00-1ce0-11e9-8782-1a2ef9106961.png)

## link
You can build iOS App in this step.
https://github.com/DroidKaigi/conference-app-2019/tree/master/frontend/ios

**Comment by ShoMasegi** [comment]
I want to try it🙋‍♂️
