### ISSUE TITLE
Apply session tag design in session detail screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#564]
## Kind (Required)

- Other

 ## Overview (Required)

- Currently, Session list.
![image](https://user-images.githubusercontent.com/1386930/51437574-7655d000-1ce3-11e9-93fa-2308186a6b65.png)
- Curretly, session detail. Please apply session detail tag colors! 🙏 
![image](https://user-images.githubusercontent.com/1386930/51437589-a3a27e00-1ce3-11e9-99b2-e1131212d5c1.png)

**Comment by NUmeroAndDev** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks!
