### ISSUE TITLE
Filtering sessions by Audience Category = "Unspecified" (指定無し) is not working

### ISSUE THREAD

**Issue by kafumi** [DroidKaigi/conference-app-2019#572]
**Overview (Required)**
- Audience Category = "Unspecified" (指定無し) filter is not working
- Even if that filter is enabled, "For Beginners" sessions are listed

**Steps To Reproduce**

1. Launch the app
2. Show session filters and enable "Unspecified" (指定無し) filter in "Audience Category" section
3. Check updated session list on Day1

**Expected behavior**
After step 3, "For Beginners" (初心者向け) sessions are filtered and not displayed on the session list.

**Actual behavior**
After step 3, All sessions including "For Beginners" (初心者向け) are listed on the session list. 

**Screenshots**
<img width="300" src="https://user-images.githubusercontent.com/12084705/51441161-fc1b5080-1cce-11e9-92cf-131077dc32e9.png" /> <img width="300" src="https://user-images.githubusercontent.com/12084705/51441162-fcb3e700-1cce-11e9-99f7-341a680de75f.png" />

**Env:**
 - Device: Android Emulator
 - OS: 9.0
 - App Version or the branch: master 540ac369ce008faf69260b037a5a60e0ca8ce333

**Additional context**
N/A

**Comment by jmatsu** [comment]
Thank you for your dedicated report!

**Comment by yh1224** [comment]
🙋‍♂️

**Comment by panpanini** [comment]
thanks! assigned 👍
