### ISSUE TITLE
Display appropriate map when going from session detail to floormap

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#581]
## Kind (Required)

- Other

 ## Overview (Required)

- When going from session detail to floormap move to the tab corresponding to the session room
- If the session room name does not contains "Hall", Please show 5F floormap
![image](https://user-images.githubusercontent.com/1386930/51512519-af0fb980-1e49-11e9-9ea1-f6875a57026f.png)
![image](https://user-images.githubusercontent.com/1386930/51512599-1c234f00-1e4a-11e9-9171-71772dea97ed.png)

 ## Links	

-

**Comment by mhidaka** [comment]
@tommykw Thanks! 
I Assigned you😉
