### ISSUE TITLE
Add  `features = ["parcelize"]` to model module.

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#582]
## Kind (Required)

- Proposal / Discussion

 ## Overview (Required)

- We are using only `parcelize`. So we can just use only `parcelize`.

https://github.com/DroidKaigi/conference-app-2019/blob/6b7f81b936e47de1bb43dbd687b158fe63088633/model/build.gradle#L12

https://github.com/JetBrains/kotlin/blob/master/libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/resources/testProject/AndroidExtensionsSpecificFeatures/app/build.gradle#L33

**Comment by NUmeroAndDev** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks always 🥇
