### ISSUE TITLE
typo Androd

### ISSUE THREAD

**Issue by a25max** [DroidKaigi/conference-app-2019#588]
**Overview (Required)**
I found small problem. 
I think the cause is the server response.Sorry to raise a problem that is not caused by the application 🙇 

**Steps To Reproduce**

1. open app.
2. tap「マルチモジュールプロジェクトでの..」

**Expected behavior**
Androd => Android

**Screenshots**
<img src="https://user-images.githubusercontent.com/11706821/51537795-da6ac680-1e92-11e9-854b-41127de12460.png" width="320">

**Env:**
 - Device: [e.g. Pixel3]
 - OS: [e.g. 9.0]
 - App Version or the branch [e.g. 0.1.0 or master]

**Additional context**

**Comment by mhidaka** [comment]
@a25max Thank you for reporting issue.
May I have a little time for confirmation with session team ? btw, good catch!

**Comment by mhidaka** [comment]
I'm afraid I do not change the session description. We are going to handle the original sentences by the authors.

Thank you for sharing your eagle eye.
