### ISSUE TITLE
MotionLayout for session detail title scrolling

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#597]
## Kind (Required)

- Proposal / Discussion

 ## Overview (Required)

- Now the title is not animated. So I want to animate it.
![motion](https://user-images.githubusercontent.com/1386930/51602741-18c3bc80-1f4b-11e9-92bc-40ba08c4bded.gif)

 ## Links	

-

**Comment by NUmeroAndDev** [comment]
I want to try it 🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned!
