### ISSUE TITLE
Fix timezone for session time table

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#615]
## Kind (Required)

- Other

 ## Overview (Required)

- 
![image](https://user-images.githubusercontent.com/1386930/51697836-1bf2a180-204c-11e9-8f4d-ad32641768d8.png)

 ## Links	

- https://github.com/DroidKaigi/conference-app-2019/search?q=timezoneoffset&unscoped_q=timezoneoffset

**Comment by offwhiite** [comment]
I want to try! ✋

**Comment by futabooo** [comment]
@offwhiite Thanks!! Assigned!!
