### ISSUE TITLE
Use SafeArgs for session time table

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#618]
## Kind (Required)

- Other

 ## Overview (Required)

- Title says everything

 ## Links	

- https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/TabularFormSessionPageFragment.kt#L94

**Comment by sobaya-0141** [comment]
やってみたいです！！

**Comment by e10dokup** [comment]
@sobaya-0141 Thanks! Please take this issue!
