### ISSUE TITLE
Open session detail when session click in session time table

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#619]
## Kind (Required)

- Other

 ## Overview (Required)

- Title says everything
![image](https://user-images.githubusercontent.com/1386930/51698599-fb2b4b80-204d-11e9-959d-421086bc3118.png)

**Comment by a25max** [comment]
🙋

**Comment by e10dokup** [comment]
@a25max Thanks! We assigned this issue to you.
