### ISSUE TITLE
Overwrite lunch session for session time table by ItemDecoration

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#620]
## Kind (Required)

- Proposal / Discussion

 ## Overview (Required)

- Currently, lunch is only HallA, But we want to spread it. It is hard to realize this with LayoutManager, so overwrite it with ItemDecoration.

![image](https://user-images.githubusercontent.com/1386930/51700339-392a6e80-2052-11e9-8243-01a8fbed6030.png)

 ## Links	

- https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/TabularFormSessionPageFragment.kt#L61

**Comment by itome** [comment]
I'll try this.

**Comment by takahirom** [comment]
Thanks! Assigned

**Comment by panpanini** [comment]
@itome How's your progress on this~? Is there something we can help with?

**Comment by itome** [comment]
I'm working on now. I'll create PR today.

**Comment by takahirom** [comment]
I'm looking forward to your PR 😄
