### ISSUE TITLE
Quit ViewPager for TabularFormSessionPagesFragment

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#622]
## Kind (Required)

- Other

 ## Overview (Required)

Because of

- Make an unintended transition.
- Use memory.
- There are few people like 2 days at the same time.

 ## Links	

- https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/TabularFormSessionPagesFragment.kt#L48

**Comment by Yuiki** [comment]
:raised_hands:

BTW, what does this mean? 
> There are few people like 2 days at the same time.

**Comment by takahirom** [comment]
Sorry for my bad English 🙏 
It means that few people want to see two tabs simultaneously. 🙇

**Comment by takahirom** [comment]
Thanks! Assigned 🙏

**Comment by Yuiki** [comment]
Never mind. I see :+1: 
Thank you.
