### ISSUE TITLE
TabularFormSessionPageFragment Day2 room 6, 7 is not found

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#627]
## Kind (Required)

- Bug report

 ## Overview (Required)

- 
![image](https://user-images.githubusercontent.com/1386930/51735912-01600d00-20cc-11e9-8a14-1524f99c26bf.png)

**Comment by aosa4054** [comment]
🙋‍♂️

**Comment by tomoya0x00** [comment]
Thanks! Assigned 👍
