### ISSUE TITLE
Swiping quickly and repeatedly on the session tab will freeze the app.

### ISSUE THREAD

**Issue by koji-1009** [DroidKaigi/conference-app-2019#635]
**Overview (Required)**

- Bug report

**Steps To Reproduce**

1. Go to "DroidKaigi:2019" home page. (in code, MainAcitivity.kt)
2. Swipe session tab quickly and repeatedly...
3. App is freezing. (Probably a mount of GC is occurring.)

**Expected behavior**

Swipe indefinitely.

**Screenshots**

![cedricopqs28 85-13-4koji01262019220650](https://user-images.githubusercontent.com/17231507/51787547-cd154b00-21b6-11e9-86aa-0e1d00f7711f.gif)

**Env:**

 - Device: Moto g5
 - OS: 8.1
 - App Version or the branch : master

**Additional context**

As I saw, the offscreenPageLimit of the ViewPager is the default.

**Comment by koji-1009** [comment]
If this issue is duplicated, please close this. 🙏

**Comment by takahirom** [comment]
Does it happen even if leakcanary is invalidated?

**Comment by koji-1009** [comment]
Oh, I try it.

**Comment by koji-1009** [comment]
@takahirom 
It is reproducible.

**Comment by koji-1009** [comment]
Maybe there is a relationship, RAM of moto g5 is only 2G.

https://www.motorola.co.jp/products/moto-g

**Comment by koji-1009** [comment]
@takahirom 
This issue is reproducible on Essential Phone.

Can I challenge this issue?

**Comment by takahirom** [comment]
@koji-1009 Thank you for investigating 👍 Assigned 👍
