### ISSUE TITLE
Show gray circle background when session speaker image not present

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#647]
## Kind (Required)

- Other

 ## Overview (Required)

- 
![image](https://user-images.githubusercontent.com/1386930/51797635-69d4f880-224a-11e9-9404-6fa6fdadafeb.png)

**Comment by tarumzu** [comment]
I'll do it.

**Comment by takahirom** [comment]
Thanks! Assigned👍
