### ISSUE TITLE
Session Detail Title with no scrolling has an invalid new line

### ISSUE THREAD

**Issue by clockvoid** [DroidKaigi/conference-app-2019#649]
## Kind (Required)

- Other

 ## Overview (Required)

- Immediately after opening the session detail, that title has an invalid new line.
![screenshot_20190127-173327](https://user-images.githubusercontent.com/6965122/51798702-35693880-225a-11e9-80a7-7d68f100e35c.png)

It's scrolling, and go back, then it's gonna be normal.

I have been able to fix it!

 ## Links	

- #597

**Comment by jmatsu** [comment]
Thank you for reporting. 

> I have been able to fix it!

Can we leave it to you?

**Comment by clockvoid** [comment]
Yes.
