### ISSUE TITLE
Open IME when app started

### ISSUE THREAD

**Issue by amay077** [DroidKaigi/conference-app-2019#656]
**Overview (Required)**
- Open IME when app started

**Steps To Reproduce**

1. Launch app
2. App launched and IME opened

**Expected behavior**

No need IME when app started

**Screenshots**
<img alt="" height="320" src="https://user-images.githubusercontent.com/401369/51810224-e1a63000-22e9-11e9-8618-b5b66f852743.gif" />

**Env:**
 - Device: Xperia XZ1 Compact
 - OS: 8.0
 - DroidKaigi 2019#898 via deploygate
- IME: ATOK

Anyone has the same issue?

**Comment by takahirom** [comment]
I can reproduce it in the emulator. Thanks 👍

**Comment by tarumzu** [comment]
@takahirom Hi, Is this issue fixed?

**Comment by takahirom** [comment]
No, I don't have a solution for this 😭

**Comment by amay077** [comment]
I still see this issue in latest DroidKaigi apps via DeployGate#908.

**Comment by tarumzu** [comment]
I'll do it!🤚

**Comment by takahirom** [comment]
Thanks 🙇 Assigned 👍
