### ISSUE TITLE
Apply timetable item design

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#658]
## Kind (Required)

- Other

 ## Overview (Required)

-
![image](https://user-images.githubusercontent.com/1386930/51817922-3d83af80-2310-11e9-836b-dca35a7a49de.png)
 
![image](https://user-images.githubusercontent.com/1386930/51817997-80de1e00-2310-11e9-8435-442dd305f96f.png)
![image](https://user-images.githubusercontent.com/1386930/51818011-876c9580-2310-11e9-8b52-2b1280f0d651.png)
![image](https://user-images.githubusercontent.com/1386930/51818024-92272a80-2310-11e9-85bb-07c04d509ac4.png)

 ## Links	

- https://gallery.io/projects/MCHbtQVoQ2HCZd9Pbpex4PVP/files/MCHtA7U1iMGr6-ZF5RXVf1KRcp6VvzOiw58
We will invite you for the gallery.

**Comment by NUmeroAndDev** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks always! Assigned
