### ISSUE TITLE
iPad Pro3 Simulator can not show first tab sessions.

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#660]
## Kind (Required)

- Bug report (please use the other template)

## Overview (Required)

-  It just shows an empty tab

**Comment by ShoMasegi** [comment]
@takahirom I can't replicate this bug.
But, I think it was caused by wrong reload timing.

**Comment by ShoMasegi** [comment]
@takahirom Please check this PR.🙇‍♂️(#666)
