### ISSUE TITLE
When day2, open day2 time table

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#661]
## Kind (Required)

- Other

 ## Overview (Required)

- Please look link, if it is 2/8 please show day2 for TabularFormSessionPagesFragment

 ## Links	

- https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SessionPagesFragment.kt#L153

**Comment by daisukemotonami** [comment]
✋🏿

**Comment by takahirom** [comment]
Thanks! Assinged 👍
