### ISSUE TITLE
Fix crash when open or clicking favorite

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#665]
**Overview (Required)**
- Crash when clicking favorite

**Steps To Reproduce**

0. Install from DeployGate
1. Click on 'favorite'
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/1386930/51836676-6b82e700-2344-11e9-9d2e-b175ea4a5ae2.png)

**Comment by nyafunta9858** [comment]
@takahirom 
Because I confirmed that I made modifications and did not crash, may I create PR?
But I do not know whether this is an appropriate correction because I don't know very much about R8 code shrink...is it OK?

**Comment by takahirom** [comment]
Thanks! It is OK!🙏
