### ISSUE TITLE
Add deeplink support

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#67]
## Overview (Required)
- We can use navigation architecture component support

**Comment by yt-tkhs** [comment]
🙋‍♂️

**Comment by jmatsu** [comment]
@yt-tkhs 
Thanks! 
Please feel free to ask us if you have any questions.

**Comment by jmatsu** [comment]
@yt-tkhs 
Hi, how is your progress? 
If you need time or want to take over this task, please don't hesitate to ask us. Thanks.

**Comment by jmatsu** [comment]
Sorry, let us add new label and the milestone.

**Comment by yt-tkhs** [comment]
Sorry for late 🙇  I haven't started work on this issue yet, but I gonna do this tomorrow.
