### ISSUE TITLE
Session message for iOS

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#673]
## Kind (Required)

- Other

 ## Overview (Required)

- 
![image](https://user-images.githubusercontent.com/1386930/51881085-2c44ac80-23bd-11e9-9b1f-f5b3b1fe60a1.png)

 ## Links	

- You can use Session.message field for it.
https://github.com/DroidKaigi/conference-app-2019/blob/master/model/src/commonMain/kotlin/Session.kt#L77

**Comment by hironytic** [comment]
🙋🏻‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned🙏
