### ISSUE TITLE
Use the production API endpoint for iOS app as well

### ISSUE THREAD

**Issue by jmatsu** [DroidKaigi/conference-app-2019#674]
## Kind (Required)

- New feature

 ## Overview (Required)

- Change api endpoints based on Schema for iOS app
- https://github.com/DroidKaigi/conference-app-2019/blob/master/data/api-impl/build.gradle#L73 should be used for the release build

 ## Links	

- https://github.com/DroidKaigi/conference-app-2019/blob/master/data/api-impl/src/iosMain/kotlin/io/github/droidkaigi/confsched2019/data/api/ApiEndpoint.kt#L3

**Comment by hironytic** [comment]
I'll give it a try 🙋‍♂️

**Comment by hironytic** [comment]
I've started working on this issue, but I have a question.
How can I build the iOS app for release?
I simply changed the build configuration to "Release" and run, then I got a linker error.
I think the reason is related this linker warning:

```
ld: warning: ignoring file /Users/ichi/Projects/private/DroidKaigi2019/conference-app-2019/frontend/ioscombined/build/xcode-frameworks/ioscombined.framework/ioscombined, file was built for x86_64 which is not the architecture being linked (i386): 
```

Can anyone tell me how? 🙏

**Comment by panpanini** [comment]
thanks, I'll assign you!

What was the command you were using to build the release app?

**Comment by hironytic** [comment]
@panpanini  Thanks for your support.
I did the following steps in Xcode:
1. Select the menu Product > Scheme > Edit Scheme
2. In the opened dialog, select "Run" on the left pane, change Build Configuration to "Release" in Info tab on the right pane.
3. Close the dialog.
4. Set destination to "iPhone XS" (simulator) via Product > Destination menu.
5. Run (Product > Run)

**Comment by takahirom** [comment]
I did the following step for release.

1. Select Generic iOS devices
![image](https://user-images.githubusercontent.com/1386930/51951687-e1886a80-2478-11e9-920a-f21a281efeb2.png)
2. Product archive

And I did your steps.
It became same error 😭

**Comment by panpanini** [comment]
Can you try checking the `Build Active Architecture Only` setting? It should be set to `No`

**Comment by panpanini** [comment]
(The problem is that for the simulator, we need an i836 library, but only an x86_64 was built)

**Comment by takahirom** [comment]
I don't know for that setting. But it relates here.
https://github.com/DroidKaigi/conference-app-2019/blob/master/frontend/ioscombined/build.gradle#L7

**Comment by hironytic** [comment]
The setting is below:

<img width="660" alt="screen shot 2019-01-30 at 11 12 57" src="https://user-images.githubusercontent.com/1498691/51953555-295ec000-2480-11e9-95e9-913fb79c69f5.png">

Anyway, I also did @takahirom way, archive targeting Generic iOS Device, but I got same error.

```
ld: warning: ignoring file /Users/ichi/Projects/private/DroidKaigi2019/conference-app-2019/frontend/ioscombined/build/xcode-frameworks/ioscombined.framework/ioscombined, file was built for x86_64 which is not the architecture being linked (arm64): /Users/ichi/Projects/private/DroidKaigi2019/conference-app-2019/frontend/ioscombined/build/xcode-frameworks/ioscombined.framework/ioscombined
```

> file was built for x86_64 which is not the architecture being linked (arm64)

I have no idea why it is built for x86_64. I think it is for simulator.

**Comment by takahirom** [comment]
Sorry, when I release it. I also did the following steps.

1. I set it 

```
iosX64('iOS')
```

↓

```
iosArm64('iOS')
```

2. Set team.

3. Archive

**Comment by hironytic** [comment]
Ah, thanks. After changing `iosX64('iOS')` to `iosArm64('iOS')` in ioscombined/build.gradle (and also changing bundle ID to my own and setting team), I finally succeeded to archive 🎉
