### ISSUE TITLE
[iOS ] Contents are not shown at bottom safe area. It's cropped.

### ISSUE THREAD

**Issue by matsujun** [DroidKaigi/conference-app-2019#675]
**Overview (Required)**
- Bottom SafeArea handling looks not following Apple's guideline.

**Steps To Reproduce**

1. Open App

**Expected behavior**
Contents are not cropped.

**Screenshots**
![ios_](https://user-images.githubusercontent.com/10704349/51883525-9f065580-23c6-11e9-94c6-d2d0910d840d.png)

**Env:**
 - Device: iPhone X
 - OS: 12.1.3
 - App Version or the branch: 1.0.0? (Initial release on AppStore)

**Additional context**
N/A

**Comment by sugoi-wada** [comment]
✋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
