### ISSUE TITLE
Add floor map screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#68]
## Overview (Required)
- We need to create the floor map screen
- The images are already added
https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/floormap/src/main/res/drawable-hdpi/ic_floor1.png

## Links
- https://gallery.io/projects/MCHbtQVoQ2HCZd9Pbpex4PVP/files/MCHtA7U1iMGr6907YDmqSpauSG02BDOsuXw (Please send request)

**Comment by androhi** [comment]
@takahirom If there is not a person to do, I want to do!

**Comment by androhi** [comment]
I sent the request to the gallery.

**Comment by panpanini** [comment]
assigned!!

**Comment by takahirom** [comment]
Thanks! approved request! 👍

**Comment by panpanini** [comment]
Thats correct! 💯
