### ISSUE TITLE
Apply toggle favorite immediately in session list.

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#683]
## Kind (Required)

- Other

 ## Overview (Required)

-  It is work in session detail. But when session lists are not applied 🤔 

 ## Links	

- Session detail: https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SessionDetailFragment.kt#L146

**Comment by kkt-yu** [comment]
🙋‍♂️

**Comment by satsukies** [comment]
Thanks! Assigned!

**Comment by takahirom** [comment]
@kkt-yu He can not this today.
I will do this 🙋
