### ISSUE TITLE
Show current time session when loading session first in Fragment

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#684]
## Kind (Required)

- Other

 ## Overview (Required)

- We want to show the current time session when conference starts
- We want to scroll to the current session when first loading.
- As there are times when the timing is severe, I think it's good to have flags like this in the Fragment flag for this, like isInitializedScrollPosition.

Now we can use `scrollToCurrentSession ` 
https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/BottomSheetDaySessionsFragment.kt#L162

**Comment by nacatl** [comment]
Can I challenge this?

And I would like to confirm, does this has a milestone as same as #434?

**Comment by panpanini** [comment]
Thanks, assigned! Lets set it as the same milestone 😉

**Comment by nacatl** [comment]
@panpanini 
Thanks!
I make it as soon as possible.
