### ISSUE TITLE
When favorited codelab sessions are starts, wrong notification is shown

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#685]
## Kind (Required)

- Other

 ## Overview (Required)

- 
![image](https://user-images.githubusercontent.com/1386930/51924404-51263780-2430-11e9-9366-30583140a9c3.png)

https://github.com/DroidKaigi/conference-app-2019/blob/master/frontendcomponent/androidcomponent/src/main/java/io/github/droidkaigi/confsched2019/util/SessionAlarm.kt#L55

**Comment by sobaya-0141** [comment]
:raising_hand_man:

**Comment by takahirom** [comment]
Thanks! Assigned 👍
