### ISSUE TITLE
Floormap for iOS

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#686]
## Kind (Required)

- Other

 ## Overview (Required)

- You can use these images. Please use that!
- https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/floormap/src/main/res/drawable-xxhdpi/ic_floor1.png
- https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/floormap/src/main/res/drawable-xxhdpi/ic_floor2.png

 ## Links	

-

**Comment by 417-72KI** [comment]
🙋🏻‍♂️

**Comment by panpanini** [comment]
Thanks!!! Assigned 💪
