### ISSUE TITLE
Add contributors screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#69]
## Overview (Required)
- We need to create the contributors screen

## Links
- https://gallery.io/projects/MCHbtQVoQ2HCZd9Pbpex4PVP/files/MCHtA7U1iMGr64hSKBFaITmFHhU5Yn4CQP8 (Please send request)

**Comment by jmatsu** [comment]
api is now ready. 
https://droidkaigi2019-dev.appspot.com/api/contributors

For more detail, please refer to https://app.swaggerhub.com/apis-docs/jmatsu/DroidKaigi2019/1.0.0

**Comment by fumiya-kume** [comment]
Maybe Contributors API is now avaivable, and i want to assinged this issue.

**Comment by takahirom** [comment]
Thanks!!
Assigned🙌

**Comment by fumiya-kume** [comment]
# memo
API Call class:
conference-app-2019/data/api-impl/src/commonMain/kotlin/io/github/droidkaigi/confsched2019/data/api/KtorDroidKaigiApi.kt
API Call Define:
conference-app-2019/data/api/src/commonMain/kotlin/io/github/droidkaigi/confsched2019/data/api/DroidKaigiApi.kt

**Comment by jmatsu** [comment]
@fumiya-kume 
Hi, thank you for working on this issue. How is your progress?
Please feel free to contact us if you need any help or want to take over this task. Thanks.

**Comment by fumiya-kume** [comment]
@jmatsu Hello, I doing this issue.
and i detect this issue time limit is ~01/20, is this OK?

**Comment by jmatsu** [comment]
What do you mean? 👀 The milestone says the date is Feb. 2, not Jan. 20. It includes the review time as well, so please be careful.

My comment was just kinda ping so we don't mean to rush you. Sorry if you feel like so.

**Comment by jmatsu** [comment]
@fumiya-kume 
We are sorry for the short notice. 
We have changed the deadline for this issue because we should consider the review time. 
Please don't hesitate to ask us if you would like to take over or need any support. Thanks.

**Comment by fumiya-kume** [comment]
Remaing Task
- Dagger Setting
- Repository Impl
Done Task
- View(xml)
- FLUX(?) Flow
- RecyclerView

@jmatsu  Sorry...

**Comment by fumiya-kume** [comment]
Can i make PR before done tasks?
ex. [WP]
