### ISSUE TITLE
Add ripple effect for TabularSpeechSessionItem,TabularServiceSessionItem

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#707]
## Kind (Required)

Choose the suitable template if exists.

- Other

 ## Overview (Required)

- 
![image](https://user-images.githubusercontent.com/1386930/52106274-7e900280-2635-11e9-98f3-037084537f3d.png)

**Comment by sobaya-0141** [comment]
:raising_hand_man:

**Comment by tomoya0x00** [comment]
Thanks! Assigned 👍

**Comment by takahirom** [comment]
@sobaya-0141 
Thank you for fast contribution as always 👍

**Comment by sobaya-0141** [comment]
@takahirom 
簡単なものばかりで申し訳ないです。。。
ちょっとずつ力を付けて貢献できるようになります！！

**Comment by takahirom** [comment]
But you are solving high priority important issues. It helps us significantly. 🙇
