### ISSUE TITLE
Announcement for iOS

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#708]
## Kind (Required)

- Other

 ## Overview (Required)

- We don't have the design for iOS. 🙇 
![image](https://user-images.githubusercontent.com/1386930/52106438-1db4fa00-2636-11e9-94be-3c347acb0314.png)

**Comment by MihoSasaki** [comment]
I'd like to try this one...!(I might release this if I cannot do this🙇‍♀️)

**Comment by takahirom** [comment]
Thanks! Assigned 🙏
