### ISSUE TITLE
Refactor for FiltersTest

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#711]
## Kind (Required)

- Other

 ## Overview (Required)

- I think we can make it more readable and simple.
- We can use Four-Phase Test (Setup, Exercise, Verify)
- We can use [speechSessionMock](https://github.com/DroidKaigi/conference-app-2019/blob/master/model/src/jvmTest/kotlin/io/github/droidkaigi/confsched2019/model/FiltersTest.kt#L115) for all tests
- If you have any improvement idea please do it 🙏 

 ## Links	

- https://github.com/DroidKaigi/conference-app-2019/blob/master/model/src/jvmTest/kotlin/io/github/droidkaigi/confsched2019/model/FiltersTest.kt

**Comment by akihito104** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned 👍
