### ISSUE TITLE
AssistedInject for TabularServiceSessionItem,TabularSpeechSessionItem

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#712]
## Kind (Required)

- Other

 ## Overview (Required)

- Please try it like [SpeechSessionItem](https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/item/SpeechSessionItem.kt#L33)

 ## Links	

- https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/item/SpeechSessionItem.kt#L33

**Comment by lcdsmao** [comment]
I want to challenge it!🙋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
