### ISSUE TITLE
Announcement deeplink

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#714]
## Kind (Required)

- Other

 ## Overview (Required)

- We should add a deep link to here for the announcement.
- https://github.com/DroidKaigi/conference-app-2019/blob/master/frontendcomponent/androidcomponent/src/main/res/navigation/navigation.xml#L128

```xml
        <deepLink app:uri="droidkaigi.jp/2019/announcement"/>
```

Probably you can check it like this

```
adb shell am start -a android.intent.action.VIEW -d "https://droidkaigi.jp/2019/announcement"
```

**Comment by nichiyoshi** [comment]
Let me try this as my first contribution🙋‍♂️

**Comment by tomoya0x00** [comment]
Thanks! Assigned 👍
