### ISSUE TITLE
Add StaffSearch ActionCreator test

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#716]
## Kind (Required)

- Other

 ## Overview (Required)

- You can see other screen tests for your reference.

 ## Links	

- StaffSearchActionCreator https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/staff/src/main/java/io/github/droidkaigi/confsched2019/staff/ui/actioncreator/StaffSearchActionCreator.kt#L18
- You can see AnnouncementActionCreatorTest https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/announcement/src/test/java/io/github/droidkaigi/confsched2019/announcement/ui/actioncreator/AnnouncementActionCreatorTest.kt#L21

**Comment by tsuyosh** [comment]
🙋🏻‍♂️
