### ISSUE TITLE
Add Contributor ActionCreator test

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#717]
## Kind (Required)

- Other

 ## Overview (Required)

- You can see other screen tests for your reference.

 ## Links	

- ContributorActionCreator https://github.com/DroidKaigi/conference-app-2019/blob/257fc9f4d3a13ae8f968b80e1878b41d30e45598/feature/contributor/src/main/java/io/github/droidkaigi/confsched2019/contributor/action/ContributorActionCreator.kt
- You can see AnnouncementActionCreatorTest https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/announcement/src/test/java/io/github/droidkaigi/confsched2019/announcement/ui/actioncreator/AnnouncementActionCreatorTest.kt#L21

**Comment by rince** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks!🙌
