### ISSUE TITLE
Add Sponsor ActionCreator test

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#718]
## Kind (Required)

- Other

 ## Overview (Required)

- You can see other screen tests for your reference.

 ## Links	

- SponsorActionCreator https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/sponsor/src/main/java/io/github/droidkaigi/confsched2019/sponsor/ui/actioncreator/SponsorActionCreator.kt#L15
- You can see AnnouncementActionCreatorTest https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/announcement/src/test/java/io/github/droidkaigi/confsched2019/announcement/ui/actioncreator/AnnouncementActionCreatorTest.kt#L21

**Comment by xnxaxo** [comment]
:hand:

**Comment by tomoya0x00** [comment]
Thanks! Assigned 👍

**Comment by xnxaxo** [comment]
@tomoya0x00 
環境の事で質問なのですが、forkしてcloneしてReadmeのRequirementsまで行ったのですが、
参考となるテストコードを開いた際に表示が真っ赤なのでテストを実行するとエラーになるのですが
行った手順以外に設定が必要なのでしょうか？
添付のような状態になっていて、アプリもビルドして端末に入るのですが、Home画面のDay1, Day2に何も表示されません。
申し訳ありませんが、わかりましたらお手数かけますがご回答のほどよろしくお願い致します.
<img width="867" alt="2019-02-02 18 24 12" src="https://user-images.githubusercontent.com/39042624/52162556-4feb5800-2719-11e9-8cb2-1b2fb48462cb.png">

**Comment by takahirom** [comment]
Can you check this?
https://github.com/DroidKaigi/conference-app-2019/issues/548

日本語で失礼します。
多分通信できてないのはエミュレータの環境のせいかもしれません。Google Playが入れられるエミュレーターでお試しください

**Comment by takahirom** [comment]
Can you try this?

in settings.gradle

```
include ':frontend:android', //':frontend:ioscombined',
```

**Comment by xnxaxo** [comment]
@takahirom 
settings.gradle tried.
The following error has been resolved.
` java.lang.Throwable: Module 'ioscombined_iOSMain' and module 'api-impl_iOSMain' have the same content root:`

However, since it was raised by another issue, I removed it from the target.

**Comment by takahirom** [comment]
Sorry, What does `I removed it from the target` mean ?
