### ISSUE TITLE
Add SessionSurvey Store test

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#720]
## Kind (Required)

- Other

 ## Overview (Required)

- You can see other screen tests for your reference.

 ## Links	

- SessionSurveyStore https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/survey/src/main/java/io/github/droidkaigi/confsched2019/survey/ui/store/SessionSurveyStore.kt#L14
- AnnouncementStoreTest https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/announcement/src/test/java/io/github/droidkaigi/confsched2019/announcement/ui/store/AnnouncementStoreTest.kt#L20

**Comment by ntsk** [comment]
🙋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
