### ISSUE TITLE
Add StaffSearch Store test

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#721]
## Kind (Required)

- Other

 ## Overview (Required)

- You can see other screen tests for your reference.

 ## Links	

- StaffSearchStore https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/staff/src/main/java/io/github/droidkaigi/confsched2019/staff/ui/store/StaffSearchStore.kt#L14
- AnnouncementStoreTest https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/announcement/src/test/java/io/github/droidkaigi/confsched2019/announcement/ui/store/AnnouncementStoreTest.kt#L20

**Comment by rwadada** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks!
