### ISSUE TITLE
Add Contributor Store test

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#722]
## Kind (Required)

Choose the suitable template if exists.

- Other

 ## Overview (Required)

- You can see other screen tests for your reference.

 ## Links	

- ContributorStore https://github.com/DroidKaigi/conference-app-2019/blob/257fc9f4d3a13ae8f968b80e1878b41d30e45598/feature/contributor/src/main/java/io/github/droidkaigi/confsched2019/contributor/store/ContributorStore.kt
- AnnouncementStoreTest https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/announcement/src/test/java/io/github/droidkaigi/confsched2019/announcement/ui/store/AnnouncementStoreTest.kt#L20

**Comment by rince** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned👍
