### ISSUE TITLE
Add Sponsor Store test

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#723]
## Kind (Required)

- Other

 ## Overview (Required)

- You can see other screen tests for your reference.

 ## Links	

- SponsorStore https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/sponsor/src/main/java/io/github/droidkaigi/confsched2019/sponsor/ui/store/SponsorStore.kt#L13
- AnnouncementStoreTest https://github.com/DroidKaigi/conference-app-2019/blob/master/feature/announcement/src/test/java/io/github/droidkaigi/confsched2019/announcement/ui/store/AnnouncementStoreTest.kt#L20

**Comment by hiji** [comment]
I want to try to this issue.

**Comment by takahirom** [comment]
Thanks! Assigned 👍

**Comment by hiji** [comment]
I am using AndroidStudio for the first time...
I am sorry for the basic things, but I want them to tell me.
- Is there something written about the procedure to build and start this application in AndroidStudio ?
- Is this Issue OK if I run the `build` Task of `:feature:sponsor` in Gradle and the test succeeds ?

**Comment by tomoya0x00** [comment]
@hiji 日本語で失礼します。

> Is there something written about the procedure to build and start this application in AndroidStudio ?

すごく雑に書くと、

1. [ここ](https://github.com/DroidKaigi/conference-app-2019#requirements) を参考に Android Studio 3.4 Beta 2 をインストール＆設定
2. このリポジトリをフォークしてクローンし、そのディレクトリをAndroid Studioで開く

です。
（ちょっと用事で席を外すので、また後ほど･･･）

**Comment by hiji** [comment]
@tomoya0x00 ありがとうございます。ではこちらも日本語で失礼します。
Androi Stduio 3.4 Beta 3

**Comment by hiji** [comment]
@tomoya0x00 ありがとうございます。ではこちらも日本語で失礼します。
READMEは確認し、Androi Studio 3.4 Beta 3 で記載されている設定はしているのですが、いくつかの警告と、 `frontend/android` で `build` タスクを実行すると途中で失敗します。
環境設定や手順が悪いのだろうと思い、どこかに何かしら他の情報が書かれているところがあれば知りたいと思い、ご質問しました。

**Comment by tomoya0x00** [comment]
@hiji
恐らくなのですが、
Android Studio 3.4 Beta 3 ですと、
https://github.com/DroidKaigi/conference-app-2019/blob/61c9d7121d54e67d63c1f609afbd69f14b5f6705/buildSrc/src/main/java/dependencies/Dep.kt#L6

**Comment by tomoya0x00** [comment]
@hiji
下記のプルリクでbeta03にあげようとしているので、少しお待ち頂けるとありがたいです🙇

https://github.com/DroidKaigi/conference-app-2019/pull/728

**Comment by tomoya0x00** [comment]
@hiji
プルリクマージされました！
