### ISSUE TITLE
When back to tabular session, the scroll progress is reset

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#741]
## Kind (Required)

- Other

 ## Overview (Required)

- Open App
- Goto tabular session
- Goto session detail
- Back to the tabular session. Scroll state is reset 😭

**Comment by sekiya9311** [comment]
🙋‍♂️

**Comment by jmatsu** [comment]
Thank you for joining! 🆒

**Comment by jmatsu** [comment]
Please feel free to ask us if you have questions.
