### ISSUE TITLE
Add SessionContents search() test

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#746]
## Kind (Required)

- Other

 ## Overview (Required)

- You can test it like FiltersTest

 ## Links	

- https://github.com/DroidKaigi/conference-app-2019/blob/master/model/src/jvmTest/kotlin/io/github/droidkaigi/confsched2019/model/FiltersTest.kt#L9

**Comment by xnxaxo** [comment]
✋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
