### ISSUE TITLE
Search crashes when type '+' to serch bar

### ISSUE THREAD

**Issue by from-unknown** [DroidKaigi/conference-app-2019#768]
**Overview (Required)**
- When type + to search bar, it crushes because it is not correct Regex.

**Steps To Reproduce**

1. Go to 'Search' page
2. Type '+'
3. App crushes

**Expected behavior**
Do not crush

**Screenshots**
<img width="300" src="https://user-images.githubusercontent.com/21967922/52177258-87cdca80-2801-11e9-81df-9e6467ab88f8.png" />

**Env:**
 - Device: Pixel2 XL emulator
 - OS: 8.1.0
 - master

**Additional context**
None

**Comment by tsuyosh** [comment]
Can I handle this issue? 🙋🏻‍♂️

**Comment by takahirom** [comment]
@tsuyosh Thanks! Assigned 👍
