### ISSUE TITLE
Sometimes second speaker doesn't appear

### ISSUE THREAD

**Issue by from-unknown** [DroidKaigi/conference-app-2019#770]
**Overview (Required)**
- when search second speaker for session, session appears but second speaker doesn't appear.

**Steps To Reproduce**

1. Go to 'search'
2. Type second speaker ex. 'chet'
3. Delete and retype
4. Sometimes second speaker doesn't appear

**Expected behavior**
Second speaker always appear

**Screenshots**
<img width="300" src="https://user-images.githubusercontent.com/21967922/52177562-2a884800-2806-11e9-97c4-189170be0fb8.gif" />

**Env:**
 - Device: Pixel 2 XL
 - OS: 8.1.0
 - master

**Additional context**
None

**Comment by tomoya0x00** [comment]
Thank you for your report 🙇

**Comment by koji-1009** [comment]
🙋🏻‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned👍
