### ISSUE TITLE
Make ← 🍔 when the screen can go by navigation drawer

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#775]
## Kind (Required)

- Other

 ## Overview (Required)

- I asked the designer. We can fix it
![image](https://user-images.githubusercontent.com/1386930/52178829-2f54f800-2816-11e9-93d1-f1705366c373.png)

- We can fix here. very easy
- https://github.com/DroidKaigi/conference-app-2019/blob/master/frontend/android/src/main/java/io/github/droidkaigi/confsched2019/ui/MainActivity.kt#L110

**Comment by sobaya-0141** [comment]
:raising_hand_man:

**Comment by takahirom** [comment]
Thanks! Assigned 👍
