### ISSUE TITLE
タイムテーブル画面でスクロールしてくと表示が乱れ、最終的にクラッシュする

### ISSUE THREAD

**Issue by nyafunta9858** [DroidKaigi/conference-app-2019#792]
**Overview (Required)**
- 

**Steps To Reproduce**

1. Go to Time table screen.
2. Change to Day2
3. Scroll and swipe (17:40までスクロールすると発生しやすい)

**Expected behavior**

**Screenshots**
[tmp2.mp4.zip](https://github.com/DroidKaigi/conference-app-2019/files/2827616/tmp2.mp4.zip)

**Env:**
 - Device: [Pixel3]
 - OS: [9.0]
 - App Version or the branch #1187

**Additional context**
this is similar to #785

**Comment by MoyuruAizawa** [comment]
I'm working on
