### ISSUE TITLE
The session message icon is shifting

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#799]
## Kind (Required)

- Other

 ## Overview (Required)

- The session message icon is shifting
![screenshot_2019-02-05-14-02-00](https://user-images.githubusercontent.com/1386930/52254083-ee143380-294e-11e9-86e7-3ee3184db0e7.jpg)

 ## Links	

-

**Comment by sugoi-wada** [comment]
🙌

**Comment by takahirom** [comment]
@sugoi-wada I am in a rush in today's release. Are you likely to finish in a few hours? 🙇

**Comment by sugoi-wada** [comment]
Yes! I'm working on this issue 👍

**Comment by takahirom** [comment]
Thanks!!!!! 😭
