### ISSUE TITLE
The place of Lunch is Hall A？

### ISSUE THREAD

**Issue by kgmyshin** [DroidKaigi/conference-app-2019#800]
## Kind (Required)

- other

 ## Overview (Required)

- Now, app say the place of lunch is Hall A. but I think another place.

<img src="https://user-images.githubusercontent.com/6851980/52265540-ace44980-2977-11e9-8f79-138a08fa50c9.png" width=300 />

**Comment by takahirom** [comment]
Thanks for informing! I delete that!
