### ISSUE TITLE
タイムライン画面で Day をタップしても現在時刻の場所に飛ばない, not move to now time at timelite page.

### ISSUE THREAD

**Issue by fumiya-kume** [DroidKaigi/conference-app-2019#819]
**Overview (Required)**
- https://pbs.twimg.com/media/Dy3vIIPUUAA3j0G.jpg:large

**Steps To Reproduce**

1. Go to 'time line page'
2. Click on 'Day Button'
4. not move now time.

**Screenshots**
https://pbs.twimg.com/media/Dy3vIIPUUAA3j0G.jpg:large

**Env:**
 - Device: Huawei P 20 lite
 - OS: 8.0
 - App Version or the branch [e.g. 0.1.0 or master]

**Comment by takahirom** [comment]
It's logic is a little difficult. But probably we can do it

**Comment by nacatl** [comment]
I made this feature, so I want to try it.

**Comment by takahirom** [comment]
Thanks! Assigned 👍
