### ISSUE TITLE
Create and use sample data directory

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#92]
## Overview (Required)
- 
![image](https://user-images.githubusercontent.com/1386930/50533326-c4efce80-0b6a-11e9-839e-ae843aa1a97d.png)

## Links
- https://segunfamisa.com/posts/sample-data-with-android-studio

**Comment by youmitsu** [comment]
🙋

**Comment by takahirom** [comment]
Thanks 👍 Assigned 🎨
