### ISSUE TITLE
Add footer for NavigationView

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#93]
## Overview (Required)

- Probably we should use custom layout for that.

- Current

![image](https://user-images.githubusercontent.com/1386930/50533537-113d0d80-0b6f-11e9-8552-fa8065be08b9.png)

-  What we want to do.
![image](https://user-images.githubusercontent.com/1386930/50533543-29149180-0b6f-11e9-8614-817ca1439101.png)

https://gallery.io/projects/MCHbtQVoQ2HCZd9Pbpex4PVP/files/MCHtA7U1iMGr6_wk8XZwCNuDoq0pXRBrYLU (Please send request)

**Comment by chibatching** [comment]
🙋‍♂️

**Comment by chibatching** [comment]
No worries!

I have a point that I can't understand clearly from the design.
Is this footer image scrolled with other menu items? or fixed on the bottom of the navigation drawer (in other words, overlay on other navigation view menu contents)?

**Comment by takahirom** [comment]
Thanks! Certainly the survey should not scroll. I have plans to meet with designers this evening so I will ask.

**Comment by takahirom** [comment]
There was a reply from the designer. It seems better not to scroll!

**Comment by chibatching** [comment]
Sorry, I have an additional question.
Where can I get or use footer logo image from?

**Comment by takahirom** [comment]
@chibatching 
Sorry for late 🙇 
You can use this image 🙏 
https://github.com/DroidKaigi/conference-app-2019/pull/314
