### ISSUE TITLE
Apply hamburger icon

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2019#97]
## Overview (Required)
- I don't have implementation idea.
![image](https://user-images.githubusercontent.com/1386930/50535263-afd76780-0b8b-11e9-810d-d3be15b63104.png)

**Comment by chibatching** [comment]
What does "apply" in the title mean?

**Comment by chibatching** [comment]
Thanks! I'll try this! 🙋‍♂️

**Comment by tomoya0x00** [comment]
Thanks! Assigned 🙏
